/**
 * Codegen for the per-site functions Worker entry.
 *
 * Given the list of `functions/`-relative handler files, emit the ESM entry
 * source that imports each module, builds the route manifest, and default-
 * exports `createFunctionsFetchHandler(manifest)`. The esbuild bundler
 * (`scripts/functions-build/bundle.mjs`) feeds this source to esbuild with the
 * `functions/` dir as the resolve root, producing one self-contained Worker.
 *
 * Pure string generation — no esbuild/Node imports, so it is Jest-testable and
 * Workers-compatible.
 */
import { filePathToRoutePattern, isReservedFunctionRoute } from './router.js';

/** Thrown when the `functions/` folder can't produce a valid router (e.g. a route collision). */
export class FunctionsBuildError extends Error {
  readonly detail?: unknown;
  constructor(message: string, detail?: unknown) {
    super(message);
    this.name = 'FunctionsBuildError';
    this.detail = detail;
  }
}

export interface GenerateEntryOptions {
  /** Import specifier (usually an absolute path) to the runtime's `createFunctionsFetchHandler`. */
  runtimeImportPath: string;
  /**
   * Stage 6.1 — the `functions/`-relative path to the site's scheduled module
   * (`_scheduled.ts`), when present. The entry imports it + passes it to
   * `createFunctionsFetchHandler` as the `scheduled` handler (the platform cron's
   * reserved-path invocation target). Absent → no scheduled wiring.
   */
  scheduledFile?: string;
}

export interface GeneratedEntry {
  source: string;
  routes: { file: string; pattern: string }[];
}

function importSpecifier(file: string): string {
  return './' + file.trim().replace(/^\.?\//, '');
}

/**
 * Generate the functions Worker entry source from a list of handler files.
 *
 * @param files - `functions/`-relative handler paths, e.g. `['api/hello.ts']`
 * @param opts - `runtimeImportPath` to `createFunctionsFetchHandler`
 * @returns the entry `source` plus the resolved `routes`
 * @throws {FunctionsBuildError} when two files map to the same route pattern
 * @example generateFunctionsWorkerEntry(['api/hello.ts'], { runtimeImportPath: '/abs/runtime.js' })
 */
export function generateFunctionsWorkerEntry(
  files: string[],
  opts: GenerateEntryOptions,
): GeneratedEntry {
  const seen = new Map<string, string>();
  const routes: { file: string; pattern: string }[] = [];

  for (const file of files) {
    const pattern = filePathToRoutePattern(file);
    if (isReservedFunctionRoute(pattern)) {
      throw new FunctionsBuildError(
        `Reserved path: "${file}" maps to ${pattern}, which the platform owns — rename this file.`,
        { pattern, file, reserved: true },
      );
    }
    const prior = seen.get(pattern);
    if (prior) {
      throw new FunctionsBuildError(
        `Route collision: "${file}" and "${prior}" both map to ${pattern}`,
        { pattern, files: [prior, file] },
      );
    }
    seen.set(pattern, file);
    routes.push({ file, pattern });
  }

  const importLines = routes.map(
    (r, i) => `import * as fn${i} from ${JSON.stringify(importSpecifier(r.file))};`,
  );
  const manifestLines = routes.map(
    (r, i) => `  { pattern: ${JSON.stringify(r.pattern)}, module: fn${i} },`,
  );

  // Stage 6.1 — wire the scheduled module (functions/_scheduled.ts) when present.
  const hasScheduled = !!opts.scheduledFile;
  const scheduledImport = hasScheduled
    ? `import * as scheduledMod from ${JSON.stringify(importSpecifier(opts.scheduledFile!))};`
    : '';
  const handlerCall = hasScheduled
    ? 'export default createFunctionsFetchHandler(manifest, { scheduled: scheduledMod });'
    : 'export default createFunctionsFetchHandler(manifest);';

  const source = [
    '// AUTO-GENERATED by scripts/functions-build — do not edit by hand.',
    `import { createFunctionsFetchHandler } from ${JSON.stringify(opts.runtimeImportPath)};`,
    ...importLines,
    ...(scheduledImport ? [scheduledImport] : []),
    '',
    'const manifest = [',
    ...manifestLines,
    '];',
    '',
    handlerCall,
    '',
  ].join('\n');

  return { source, routes };
}
