import { defineFeatureManifest } from '@projectsites/feature-manifests';
export default defineFeatureManifest({
  slug: 'ai_gateway_guardrails',
  name: 'AI Gateway Guardrails',
  description: 'Classifies user text via Llama Guard 3-8B and blocks requests scoring unsafe at or above 0.85 confidence threshold.',
  lifecycle: 'alpha',
  flagKey: 'ai_gateway_guardrails',
  owner: 'brian@megabyte.space',
  createdAt: '2026-06-17',
  updatedAt: '2026-06-17',
  routes: [],
  apiRoutes: ['POST /api/guardrails/check'],
  permissions: ['site:read'],
  dependencies: [],
  e2eTests: [],
  unitTests: ['../libs/features/ai_gateway_guardrails/__tests__/ai_gateway_guardrails.test.ts'],
  integrationTests: [],
  testStatus: 'partial',
  zodSchemas: ['schemas.ts'],
  observability: { sentry: true, logs: true, analytics: true },
  rollout: { defaultEnabled: false, environments: { development: true }, notes: 'Enable globally to guard all AI surfaces.' },
  risks: ['False positives may block legitimate content. Threshold is configurable via the service.'],
  removalNotes: 'Drop /api/guardrails routes. The guard() helper can remain as a no-op shim.',
});
