-- 0048_billing_events.sql
--
-- Unified billing audit log per the platform-rebuild brief.
--
-- Why a separate table from the existing infra:
--   - `webhook_events` (0001) — generic across stripe/dub/chatwoot/novu/lago. Stores
--     incoming-webhook-by-provider with status + retry count. Operational, not billing-shaped.
--   - `wallet_transactions` (0036) — per-org wallet ledger (credit/debit/refund). Internal
--     accounting unit, not the externally-visible Stripe billing surface.
--   - `usage_events` (0022) — per-org/per-site/per-metric usage rows that get forwarded to
--     Stripe meters. Pre-billing, not post-billing.
--   - `billing_events` (THIS) — the externally-anchored audit log: every Stripe charge,
--     meter report, refund, dispute, and subscription state change with the Stripe object
--     id of record. Built so an auditor can reconstruct any month's invoice from this table
--     alone without scanning webhook_events.
--
-- Cross-references the three tables above via FK-ish soft refs (no hard FKs since the
-- audit log MUST outlive a deleted org/site/transaction — required for tax / 7-yr retention).

CREATE TABLE IF NOT EXISTS billing_events (
  -- Internal id (uuid v4 generated by app code).
  id TEXT PRIMARY KEY,

  -- Org context. Soft ref (no FK) so deleting an org doesn't cascade-nuke audit trail.
  org_id TEXT NOT NULL,

  -- One of:
  --   charge.succeeded, charge.failed, charge.refunded, charge.dispute.created
  --   invoice.paid, invoice.payment_failed, invoice.finalized, invoice.voided
  --   subscription.created, subscription.updated, subscription.deleted
  --   meter.event.reported, meter.event.failed
  --   payment_method.attached, payment_method.detached
  --   refund.created, refund.updated, dispute.funds_withdrawn, dispute.closed
  --   wallet.topup, wallet.adjustment
  event_type TEXT NOT NULL,

  -- Source — what wrote this row:
  --   'stripe_webhook' = inbound webhook landed (also linked via webhook_event_id)
  --   'meter_report'   = outbound POST /v1/billing/meter_events from the worker
  --   'wallet_action'  = internal wallet ledger entry mirrored here for audit
  --   'manual'         = super-admin adjustment via /super-admin
  source TEXT NOT NULL CHECK (source IN ('stripe_webhook', 'meter_report', 'wallet_action', 'manual')),

  -- The Stripe object id of record (ch_*, pi_*, sub_*, evt_*, mtr_*, in_*, etc.)
  -- Source of truth for reconciliation against Stripe dashboard.
  stripe_object_id TEXT,
  stripe_event_id TEXT,           -- evt_* if this came from a webhook
  stripe_object_type TEXT,        -- 'charge', 'invoice', 'subscription', 'meter_event', ...

  -- Money: signed cents (+ = revenue / credit, - = refund / debit).
  -- Currency is ISO 4217 lowercase (matches Stripe API). Default to usd which covers >99% of activity.
  amount_cents INTEGER,
  currency TEXT NOT NULL DEFAULT 'usd',

  -- Optional per-site dimension. The platform-rebuild brief specifically called out
  -- per-site usage-based billing — index this column so monthly per-site rollups are O(N) reads.
  site_id TEXT,

  -- Cross-link to webhook_events row (when source = 'stripe_webhook').
  webhook_event_id TEXT REFERENCES webhook_events(id) ON DELETE SET NULL,

  -- Cross-link to wallet_transactions row (when source = 'wallet_action').
  wallet_transaction_id TEXT,

  -- Cross-link to usage_events row (when source = 'meter_report').
  usage_event_id TEXT,

  -- For meter reports: which metric was reported (matches usage_events.metric).
  metric TEXT,

  -- Free-form structured payload — R2 pointer for the full Stripe object json,
  -- not inlined to keep row size bounded.
  payload_pointer TEXT,
  payload_hash TEXT,

  -- Customer-visible result. Lets the dashboard show "5 successful charges, 1 disputed"
  -- without rejoining to webhook_events for status.
  result TEXT NOT NULL DEFAULT 'ok' CHECK (result IN ('ok', 'pending', 'failed', 'disputed', 'refunded')),

  -- Free-form error text when result = failed / disputed.
  error_message TEXT,

  -- Idempotency: every meter report must have a deterministic key so retries don't
  -- double-bill. Stripe webhooks bring evt_* which is unique; meter reports bring
  -- our own (org_id + metric + bucket_ts) hash.
  idempotency_key TEXT,

  -- Audit timestamps. created_at = when WE recorded it. occurred_at = when Stripe says it happened.
  -- Reconciling against monthly invoice uses occurred_at; debugging stuck rows uses created_at.
  occurred_at TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),

  -- One row per (source, idempotency_key) — replays no-op.
  UNIQUE (source, idempotency_key)
);

-- Hot paths.
CREATE INDEX IF NOT EXISTS idx_billing_events_org_occurred
  ON billing_events (org_id, occurred_at DESC);
CREATE INDEX IF NOT EXISTS idx_billing_events_site_occurred
  ON billing_events (site_id, occurred_at DESC) WHERE site_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_billing_events_event_type
  ON billing_events (event_type, occurred_at DESC);
CREATE INDEX IF NOT EXISTS idx_billing_events_stripe_object
  ON billing_events (stripe_object_id) WHERE stripe_object_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_billing_events_failures
  ON billing_events (result, occurred_at DESC) WHERE result IN ('failed', 'disputed');
CREATE INDEX IF NOT EXISTS idx_billing_events_pending_meter
  ON billing_events (source, result) WHERE source = 'meter_report' AND result = 'pending';

-- Monthly per-org revenue rollup view — read by /admin/billing and /super-admin reports.
-- Materialized-as-needed; D1 ANALYZE picks it up on the first /admin/billing hit.
CREATE VIEW IF NOT EXISTS v_billing_monthly_per_org AS
  SELECT
    org_id,
    substr(occurred_at, 1, 7) AS month,   -- 'YYYY-MM'
    SUM(CASE WHEN amount_cents > 0 THEN amount_cents ELSE 0 END) AS gross_revenue_cents,
    SUM(CASE WHEN amount_cents < 0 THEN -amount_cents ELSE 0 END) AS refunds_cents,
    SUM(amount_cents) AS net_cents,
    COUNT(*) AS event_count,
    SUM(CASE WHEN result = 'failed' THEN 1 ELSE 0 END) AS failed_count,
    SUM(CASE WHEN result = 'disputed' THEN 1 ELSE 0 END) AS disputed_count
  FROM billing_events
  WHERE result IN ('ok', 'failed', 'disputed', 'refunded')
  GROUP BY org_id, month;

-- Per-site, per-month rollup — drives the dashboard "Sites this month" panel and the
-- monthly invoice line items when bill is generated.
CREATE VIEW IF NOT EXISTS v_billing_monthly_per_site AS
  SELECT
    org_id,
    site_id,
    substr(occurred_at, 1, 7) AS month,
    metric,
    SUM(CASE WHEN amount_cents > 0 THEN amount_cents ELSE 0 END) AS billed_cents,
    SUM(amount_cents) AS net_cents,
    COUNT(*) AS event_count
  FROM billing_events
  WHERE site_id IS NOT NULL
  GROUP BY org_id, site_id, month, metric;

-- Last-7-day failure rate per org — drives the "Billing health" red badge in admin.
CREATE VIEW IF NOT EXISTS v_billing_health_7d AS
  SELECT
    org_id,
    COUNT(*) AS total,
    SUM(CASE WHEN result = 'failed' THEN 1 ELSE 0 END) AS failed,
    SUM(CASE WHEN result = 'disputed' THEN 1 ELSE 0 END) AS disputed,
    CAST(SUM(CASE WHEN result IN ('failed','disputed') THEN 1 ELSE 0 END) AS REAL) / NULLIF(COUNT(*), 0) AS error_rate
  FROM billing_events
  WHERE occurred_at >= date('now', '-7 days')
  GROUP BY org_id;
