-- 0580_better_auth_schema.sql
-- Better Auth schema (core + twoFactor/passkey/organization/sso/apiKey).
-- Generated by scripts/gen-better-auth-schema.mjs (compileMigrations). Static
-- migration because BA runtime auto-migrate fails on D1 (kysely-d1 introspection).

CREATE TABLE IF NOT EXISTS "user" ("id" text not null primary key, "name" text not null, "email" text not null unique, "emailVerified" integer not null, "image" text, "createdAt" date not null, "updatedAt" date not null, "twoFactorEnabled" integer, "role" text, "banned" integer, "banReason" text, "banExpires" date, "isAnonymous" integer, "username" text unique, "displayUsername" text);

CREATE TABLE IF NOT EXISTS "session" ("id" text not null primary key, "expiresAt" date not null, "token" text not null unique, "createdAt" date not null, "updatedAt" date not null, "ipAddress" text, "userAgent" text, "userId" text not null references "user" ("id") on delete cascade, "activeOrganizationId" text, "impersonatedBy" text);

CREATE TABLE IF NOT EXISTS "account" ("id" text not null primary key, "accountId" text not null, "providerId" text not null, "userId" text not null references "user" ("id") on delete cascade, "accessToken" text, "refreshToken" text, "idToken" text, "accessTokenExpiresAt" date, "refreshTokenExpiresAt" date, "scope" text, "password" text, "createdAt" date not null, "updatedAt" date not null);

CREATE TABLE IF NOT EXISTS "verification" ("id" text not null primary key, "identifier" text not null, "value" text not null, "expiresAt" date not null, "createdAt" date not null, "updatedAt" date not null);

CREATE TABLE IF NOT EXISTS "twoFactor" ("id" text not null primary key, "secret" text not null, "backupCodes" text not null, "userId" text not null references "user" ("id") on delete cascade, "verified" integer, "failedVerificationCount" integer, "lockedUntil" date);

CREATE TABLE IF NOT EXISTS "organization" ("id" text not null primary key, "name" text not null, "slug" text not null unique, "logo" text, "createdAt" date not null, "metadata" text);

CREATE TABLE IF NOT EXISTS "member" ("id" text not null primary key, "organizationId" text not null references "organization" ("id") on delete cascade, "userId" text not null references "user" ("id") on delete cascade, "role" text not null, "createdAt" date not null);

CREATE TABLE IF NOT EXISTS "invitation" ("id" text not null primary key, "organizationId" text not null references "organization" ("id") on delete cascade, "email" text not null, "role" text, "status" text not null, "expiresAt" date not null, "createdAt" date not null, "inviterId" text not null references "user" ("id") on delete cascade);

CREATE TABLE IF NOT EXISTS "passkey" ("id" text not null primary key, "name" text, "publicKey" text not null, "userId" text not null references "user" ("id") on delete cascade, "credentialID" text not null, "counter" integer not null, "deviceType" text not null, "backedUp" integer not null, "transports" text, "createdAt" date, "aaguid" text);

CREATE TABLE IF NOT EXISTS "ssoProvider" ("id" text not null primary key, "issuer" text not null, "oidcConfig" text, "samlConfig" text, "userId" text not null references "user" ("id") on delete cascade, "providerId" text not null unique, "organizationId" text, "domain" text not null);

CREATE TABLE IF NOT EXISTS "apikey" ("id" text not null primary key, "configId" text not null, "name" text, "start" text, "referenceId" text not null, "prefix" text, "key" text not null, "refillInterval" integer, "refillAmount" integer, "lastRefillAt" date, "enabled" integer, "rateLimitEnabled" integer, "rateLimitTimeWindow" integer, "rateLimitMax" integer, "requestCount" integer, "remaining" integer, "lastRequest" date, "expiresAt" date, "createdAt" date not null, "updatedAt" date not null, "permissions" text, "metadata" text);

CREATE INDEX IF NOT EXISTS "session_userId_idx" on "session" ("userId");

CREATE INDEX IF NOT EXISTS "account_userId_idx" on "account" ("userId");

CREATE INDEX IF NOT EXISTS "verification_identifier_idx" on "verification" ("identifier");

CREATE INDEX IF NOT EXISTS "twoFactor_secret_idx" on "twoFactor" ("secret");

CREATE INDEX IF NOT EXISTS "twoFactor_userId_idx" on "twoFactor" ("userId");

CREATE UNIQUE INDEX IF NOT EXISTS "organization_slug_uidx" on "organization" ("slug");

CREATE INDEX IF NOT EXISTS "member_organizationId_idx" on "member" ("organizationId");

CREATE INDEX IF NOT EXISTS "member_userId_idx" on "member" ("userId");

CREATE INDEX IF NOT EXISTS "invitation_organizationId_idx" on "invitation" ("organizationId");

CREATE INDEX IF NOT EXISTS "invitation_email_idx" on "invitation" ("email");

CREATE INDEX IF NOT EXISTS "passkey_userId_idx" on "passkey" ("userId");

CREATE INDEX IF NOT EXISTS "passkey_credentialID_idx" on "passkey" ("credentialID");

CREATE INDEX IF NOT EXISTS "apikey_configId_idx" on "apikey" ("configId");

CREATE INDEX IF NOT EXISTS "apikey_referenceId_idx" on "apikey" ("referenceId");

CREATE INDEX IF NOT EXISTS "apikey_key_idx" on "apikey" ("key");
