/**
 * Feature manifest for {{slug}}.
 *
 * @remarks
 * Generated by `npm run gen:feature -- --slug {{slug}} --name "{{Name}}"`.
 * Edit this file to describe surfaces, API routes, and migration details.
 *
 * @see {@link https://projectsites.dev/docs/architecture/feature-flags.md}
 */

export interface FeatureManifest {
  /** Kebab-case identifier matching the flag registry key. */
  slug: string;
  /** Human-readable display name. */
  name: string;
  /** 30–200 char description shown in /admin/feature-flags. */
  description: string;
  /** Feature flag key in FLAG_REGISTRY (always snake_case of slug). */
  flagKey: string;
  /** GitHub handle or email of the DRI. */
  owner: string;
  /** Hono API sub-app mount path(s). */
  apiPaths: string[];
  /** Angular/React route paths exposed by this feature. */
  uiPaths: string[];
  /** D1 migration file(s) that must run before enabling. */
  migrations: string[];
}

/** @internal — call {@link defineFeatureManifest} instead. */
function defineFeatureManifest(manifest: FeatureManifest): Readonly<FeatureManifest> {
  return Object.freeze(manifest);
}

export const manifest = defineFeatureManifest({
  slug: '{{slug}}',
  name: '{{Name}}',
  description: 'TODO: Fill in a 30–200 char description of {{slug}}.',
  flagKey: '{{SLUG_UPPER}}' /* keep snake_case */,
  owner: '{{owner}}',
  apiPaths: ['/api/{{slug}}'],
  uiPaths: ['/admin/{{slug}}'],
  migrations: [],
});
