name = "projectsites-site-health"
main = "worker.ts"
compatibility_date = "2025-04-01"

[triggers]
crons = ["*/5 * * * *"]

[[d1_databases]]
binding = "DB"
database_name = "project-sites-db-production"
database_id = "ea3e839a-c641-4861-ae30-dfc63bff8032"

[[workflows]]
binding = "SITE_WORKFLOW"
name = "site-generation"

[vars]
ADMIN_EMAIL = "brian@megabyte.space"
HEALTH_CHECK_USER_AGENT = "ProjectSites-HealthCheck/1.0"

[observability]
enabled = true
