import { defineFeatureManifest } from '@projectsites/feature-manifests';
export default defineFeatureManifest({
  slug: 'site_semantic_search',
  name: 'Site Semantic Search',
  description: 'Semantic vector search over site content using Vectorize embeddings, enabling RAG grounding for AI features and visitor search UX.',
  lifecycle: 'alpha',
  flagKey: 'site_semantic_search',
  owner: 'brian@megabyte.space',
  createdAt: '2026-06-17',
  updatedAt: '2026-06-17',
  routes: [],
  apiRoutes: ['POST /api/site-search/:siteId/query', 'POST /api/site-search/:siteId/reindex'],
  permissions: ['site:read', 'site:write'],
  dependencies: [],
  e2eTests: [],
  unitTests: ['../libs/features/site_semantic_search/__tests__/site_semantic_search.test.ts'],
  integrationTests: [],
  testStatus: 'partial',
  zodSchemas: ['schemas.ts'],
  observability: { sentry: true, logs: true, analytics: false },
  rollout: { defaultEnabled: false, environments: { development: true }, notes: 'Disabled by default.' },
  risks: ['Vectorize index must be populated before queries return results.'],
  removalNotes: 'Drop /api/site-search routes and flush the rag_chunks table rows for the site.',
});
