/**
 * @module libs/features/code_export/service
 *
 * Pure CF project generator — produces a self-contained, deployable Cloudflare
 * Worker project from site content + bindings.  Zero I/O, deterministic.
 *
 * The generated project includes:
 * - wrangler.toml with typed bindings
 * - src/index.ts (Hono Worker serving static files from R2)
 * - migrations/ (D1 schema + optional data)
 * - public/ (static assets)
 * - README.md with deploy instructions
 * - package.json with required dependencies
 * - tsconfig.json
 *
 * @example
 * ```ts
 * const project = generateCfProject({
 *   slug: 'my-site',
 *   d1DatabaseId: 'abc-123',
 *   d1DatabaseName: 'my-site-db',
 *   r2BucketName: 'my-site-assets',
 *   pages: [{ path: '/', title: 'Home', content: '<h1>Hello</h1>' }],
 * });
 * // project.files → [{ path: 'wrangler.toml', content: '…' }, …]
 * ```
 */
import type { CfProjectManifest, GeneratedFile, SiteBindings } from './schemas.js';

// ── Constants ───────────────────────────────────────────────────────────────

const COMPAT_DATE = '2026-07-15';
const COMPAT_FLAGS = ['nodejs_compat'];
const WORKER_NAME_SUFFIX = '-site';

// ── Template generators (pure, zero-I/O) ────────────────────────────────────

/**
 * Generates wrangler.toml with typed bindings for the exported site.
 *
 * Includes: D1 database binding, R2 bucket binding, KV namespace binding
 * (if configured), custom domain route (if primary hostname set), and
 * compatibility flags.
 */
function generateWranglerToml(bindings: SiteBindings): string {
  const lines: string[] = [
    `# ${bindings.slug} — Cloudflare Worker`,
    `# Generated by ProjectSites.dev Code Export`,
    `# Generated at: ${new Date().toISOString()}`,
    '',
    `name = "${bindings.slug}${WORKER_NAME_SUFFIX}"`,
    `main = "src/index.ts"`,
    `compatibility_date = "${COMPAT_DATE}"`,
    `compatibility_flags = [${COMPAT_FLAGS.map((f) => `"${f}"`).join(', ')}]`,
    '',
  ];

  // D1 binding
  if (bindings.d1DatabaseName) {
    lines.push('# D1 database — system of record for site content');
    lines.push('[[d1_databases]]');
    lines.push(`binding = "DB"`);
    lines.push(`database_name = "${bindings.d1DatabaseName}"`);
    if (bindings.d1DatabaseId) {
      lines.push(`database_id = "${bindings.d1DatabaseId}"`);
    }
    lines.push('');
  }

  // R2 binding
  if (bindings.r2BucketName) {
    lines.push('# R2 bucket — static site assets');
    lines.push('[[r2_buckets]]');
    lines.push(`binding = "ASSETS"`);
    lines.push(`bucket_name = "${bindings.r2BucketName}"`);
    lines.push('');
  }

  // KV binding
  if (bindings.kvNamespaceName) {
    lines.push('# KV namespace — cache + config');
    lines.push('[[kv_namespaces]]');
    lines.push(`binding = "CACHE"`);
    if (bindings.kvNamespaceId) {
      lines.push(`id = "${bindings.kvNamespaceId}"`);
    }
    lines.push('');
  }

  // Custom domain route
  if (bindings.primaryHostname) {
    lines.push('# Custom domain');
    lines.push('[[routes]]');
    lines.push(`pattern = "${bindings.primaryHostname}"`);
    lines.push('custom_domain = true');
    lines.push('');
  }

  // Vars
  lines.push('[vars]');
  lines.push(`SITE_SLUG = "${bindings.slug}"`);
  lines.push(`SITES_SUFFIX = "projectsites.dev"`);
  lines.push('');

  // Env
  lines.push('[env.production]');
  lines.push('workers_dev = true');
  lines.push('');

  return lines.join('\n');
}

/**
 * Generates the Worker entry point — a Hono app that serves static assets from
 * R2 and falls back to the homepage for client-side routing.
 */
function generateWorkerIndex(bindings: SiteBindings): string {
  const routes = bindings.pages
    .map((p) => `  app.get('${p.path}', async (c) => {`)
    .join('\n');

  return `/**
 * ${bindings.slug} — Worker entry point
 *
 * Generated by ProjectSites.dev Code Export.
 * Deploy: npx wrangler deploy
 * Dev:    npx wrangler dev
 */
import { Hono } from 'hono';

interface Env {
  DB: D1Database;
  ASSETS: R2Bucket;
  CACHE?: KVNamespace;
  SITE_SLUG: string;
  SITES_SUFFIX: string;
}

const app = new Hono<{ Bindings: Env }>();

// ── Health check ────────────────────────────────────────────────────────────

app.get('/health', (c) => c.json({ status: 'ok', site: '${bindings.slug}' }));

// ── Static asset serving from R2 ────────────────────────────────────────────

app.get('/assets/*', async (c) => {
  const key = c.req.path.replace(/^\\/assets\\//, '');
  const object = await c.env.ASSETS.get(key);
  if (!object) return c.notFound();
  const headers = new Headers();
  if (object.httpMetadata?.contentType) {
    headers.set('content-type', object.httpMetadata.contentType);
  }
  object.writeHttpMetadata(headers);
  return new Response(object.body, { headers });
});

// ── Sitemap ─────────────────────────────────────────────────────────────────

const SITEMAP_ROUTES = ${JSON.stringify(bindings.pages.map((p) => p.path))};

app.get('/sitemap.xml', (c) => {
  const urls = SITEMAP_ROUTES.map(
    (path) => \`  <url><loc>https://\${c.req.url.replace(/\\/sitemap\\.xml.*$/, '')}\${path}</loc></url>\`
  ).join('\\n');
  return c.html(\`<?xml version="1.0" encoding="UTF-8"?>\\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\\n\${urls}\\n</urlset>\`);
});

// ── Catch-all — serve homepage for client-side routing ──────────────────────

app.get('*', async (c) => {
  const object = await c.env.ASSETS.get('index.html');
  if (!object) return c.html('<h1>${bindings.slug}</h1><p>Site coming soon.</p>');
  const headers = new Headers();
  headers.set('content-type', 'text/html; charset=utf-8');
  object.writeHttpMetadata(headers);
  return new Response(object.body, { headers });
});

export default app;
`;
}

/**
 * Generates package.json with the minimal dependencies for the exported Worker.
 */
function generatePackageJson(bindings: SiteBindings): string {
  return JSON.stringify(
    {
      name: `${bindings.slug}-site`,
      version: '1.0.0',
      private: true,
      type: 'module',
      scripts: {
        dev: 'wrangler dev',
        deploy: 'wrangler deploy',
        'cf-typegen': 'wrangler types',
      },
      dependencies: {
        hono: '^4.6.0',
      },
      devDependencies: {
        wrangler: '^4.0.0',
        '@cloudflare/workers-types': '^4.0.0',
        typescript: '^5.9.0',
      },
    },
    null,
    2,
  );
}

/**
 * Generates tsconfig.json for the exported Worker.
 */
function generateTsconfig(): string {
  return JSON.stringify(
    {
      compilerOptions: {
        target: 'ES2022',
        module: 'ES2022',
        moduleResolution: 'bundler',
        lib: ['ES2022'],
        types: ['@cloudflare/workers-types'],
        strict: true,
        noEmit: true,
        esModuleInterop: true,
        skipLibCheck: true,
        forceConsistentCasingInFileNames: true,
        resolveJsonModule: true,
        isolatedModules: true,
        verbatimModuleSyntax: true,
      },
      include: ['src'],
    },
    null,
    2,
  );
}

/**
 * Generates README.md with deploy instructions specific to this export.
 */
function generateReadme(bindings: SiteBindings): string {
  const hasCustomDomain = Boolean(bindings.primaryHostname);
  return `# ${bindings.slug}

Generated by [ProjectSites.dev](https://projectsites.dev) Code Export.

## Quick start

\`\`\`bash
npm install
npx wrangler dev
\`\`\`

## Deploy to Cloudflare

\`\`\`bash
npx wrangler deploy
\`\`\`

${hasCustomDomain ? `Custom domain: **${bindings.primaryHostname}** will be provisioned on first deploy.` : 'Your site will be available at `https://' + bindings.slug + WORKER_NAME_SUFFIX + '.<your-subdomain>.workers.dev`.'}

## Project structure

| Path | Purpose |
|------|---------|
| \`src/index.ts\` | Worker entry point (Hono) — serves static assets + routes |
| \`wrangler.toml\` | Cloudflare configuration with typed bindings |
| \`migrations/\` | D1 database schema + optional seed data |
| \`public/\` | Static assets (HTML, CSS, JS, images) |
| \`package.json\` | Dependencies (hono, wrangler, typescript) |
| \`tsconfig.json\` | TypeScript configuration |

## Bindings

${bindings.d1DatabaseName ? `- **D1**: \`${bindings.d1DatabaseName}\` — system of record` : ''}
${bindings.r2BucketName ? `- **R2**: \`${bindings.r2BucketName}\` — static assets` : ''}
${bindings.kvNamespaceName ? `- **KV**: \`${bindings.kvNamespaceName}\` — cache + config` : ''}

## Post-deploy

1. Verify: \`curl https://<your-worker>.<subdomain>.workers.dev/health\`
2. Upload static assets to R2 (see \`scripts/upload-assets.sh\`)
3. Apply D1 migrations: \`npx wrangler d1 execute ${bindings.d1DatabaseName || '<db-name>'} --file migrations/0001_schema.sql\`
${hasCustomDomain ? '4. Set up custom domain DNS per Cloudflare instructions' : ''}

## Self-host on your own Cloudflare account

This project is a standard Cloudflare Worker. You own the code, the data, and
the deployment. No lock-in. No platform dependency. Deploy to any Cloudflare
account with \`npx wrangler deploy\`.

Built with [ProjectSites.dev](https://projectsites.dev) — the AI agent that builds, deploys, and maintains your site.
`;
}

// ─── Main generator ─────────────────────────────────────────────────────────

/**
 * Generates a complete, deployable Cloudflare Worker project from site bindings.
 *
 * The returned manifest contains every file needed to run the site as a
 * standalone Worker — just unzip, `npm install`, and `npx wrangler deploy`.
 *
 * @param bindings - Site configuration including slug, pages, assets, and CF resource IDs.
 * @returns A typed manifest with all generated project files.
 *
 * @example
 * ```ts
 * const project = generateCfProject({
 *   slug: 'my-bakery',
 *   d1DatabaseName: 'my-bakery-db',
 *   r2BucketName: 'my-bakery-assets',
 *   pages: [{ path: '/', title: 'Home', content: '<h1>Welcome</h1>' }],
 * });
 * // Use project.files to build a zip download.
 * ```
 */
export function generateCfProject(bindings: SiteBindings): CfProjectManifest {
  // Defensive defaults — callers may pass plain objects without Zod defaults.
  const b = {
    ...bindings,
    pages: bindings.pages ?? [],
    staticAssets: bindings.staticAssets ?? [],
    d1Schema: bindings.d1Schema ?? [],
    d1Data: bindings.d1Data ?? [],
  };

  const files: GeneratedFile[] = [];
  const push = (path: string, content: string) => {
    files.push({
      path,
      content,
      sizeBytes: new TextEncoder().encode(content).length,
    });
  };

  // Core config files
  push('wrangler.toml', generateWranglerToml(bindings));
  push('package.json', generatePackageJson(bindings));
  push('tsconfig.json', generateTsconfig());
  push('README.md', generateReadme(bindings));

  // Worker source
  push('src/index.ts', generateWorkerIndex(bindings));

  // D1 migrations
  if (b.d1Schema.length > 0) {
    push(
      'migrations/0001_schema.sql',
      [
        '-- Generated by ProjectSites.dev Code Export',
        `-- Site: ${bindings.slug}`,
        '',
        ...b.d1Schema,
      ].join('\n'),
    );
  }

  if (b.d1Data.length > 0) {
    push(
      'migrations/0002_seed.sql',
      [
        '-- Generated by ProjectSites.dev Code Export',
        `-- Site: ${bindings.slug}`,
        '-- ⚠️ Review before applying — contains your site data.',
        '',
        ...b.d1Data,
      ].join('\n'),
    );
  }

  // Static assets
  for (const asset of b.staticAssets) {
    push(`public/${asset.path}`, asset.content);
  }

  // Upload helper script
  push(
    'scripts/upload-assets.sh',
    [
      '#!/usr/bin/env bash',
      '# Upload static assets to R2',
      '# Generated by ProjectSites.dev Code Export',
      `set -euo pipefail`,
      '',
      `BUCKET="${bindings.r2BucketName || '<your-bucket>'}"`,
      '',
      'echo "Uploading static assets to R2 bucket: $BUCKET"',
      'for file in public/*; do',
      '  key="${file#public/}"',
      '  echo "  $key"',
      '  npx wrangler r2 object put "$BUCKET/$key" --file "$file"',
      'done',
      '',
      'echo "Done. Assets live at https://<your-worker>.<subdomain>.workers.dev/assets/<key>"',
    ].join('\n'),
  );

  const totalSize = files.reduce((sum, f) => sum + f.sizeBytes, 0);

  return {
    projectName: `${bindings.slug}${WORKER_NAME_SUFFIX}`,
    generatedAt: new Date().toISOString(),
    files,
    totalSize,
    fileCount: files.length,
    d1Binding: 'DB',
    r2Binding: 'ASSETS',
  };
}
