/**
 * @module auth_magic
 * @description Pure HMAC-signed magic link token generation and verification.
 *
 * Unlike `auth.ts` (which stores token hashes in D1), this module is stateless:
 * the token is self-contained (email + expiry + HMAC signature). Verification
 * requires only the secret — no database lookup.
 *
 * Token format:
 * ```
 * <base64url(email|expiry_ms)>.<base64url(hmac-sha256)>
 * ```
 *
 * @example
 * ```ts
 * import { generateMagicToken, verifyMagicToken, MAGIC_LINK_TTL } from './auth_magic.js';
 *
 * const token = await generateMagicToken('user@example.com', 'shared-secret');
 * // → "dXNlckBleGFtcGxlLmNvbXwx...<sig>"
 *
 * const email = await verifyMagicToken(token, 'shared-secret');
 * // → "user@example.com"
 *
 * const expired = await verifyMagicToken(token, 'wrong-secret');
 * // → null
 * ```
 *
 * @packageDocumentation
 */

import { hmacSha256 } from '@project-sites/shared';
import { timingSafeEqual } from '../lib/timing_safe_equal.js';

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

/** Default TTL for magic link tokens: 15 minutes (in milliseconds). */
export const MAGIC_LINK_TTL = 900_000;

// ---------------------------------------------------------------------------
// Internal helpers (not exported)
// ---------------------------------------------------------------------------

/**
 * Encode a string as URL-safe base64 (no padding, no +/=).
 *
 * @param raw  - UTF-8 string to encode.
 * @returns URL-safe base64 string.
 */
function base64UrlEncode(raw: string): string {
  const bytes = new TextEncoder().encode(raw);
  let binary = '';
  for (let i = 0; i < bytes.length; i++) {
    binary += String.fromCharCode(bytes[i]!);
  }
  return btoa(binary).replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '');
}

/**
 * Decode a URL-safe base64 string back to a UTF-8 string.
 *
 * @param encoded - URL-safe base64 string.
 * @returns Decoded UTF-8 string, or `null` on parse failure.
 */
function base64UrlDecode(encoded: string): string | null {
  try {
    const base64 = encoded.replace(/-/g, '+').replace(/_/g, '/');
    const binary = atob(base64);
    const bytes = new Uint8Array(binary.length);
    for (let i = 0; i < binary.length; i++) {
      bytes[i] = binary.charCodeAt(i);
    }
    return new TextDecoder().decode(bytes);
  } catch {
    return null;
  }
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Generate an HMAC-signed magic link token.
 *
 * The token embeds the email and an expiry timestamp, signed with the shared
 * secret via HMAC-SHA256. No server-side state is needed to verify it later.
 *
 * @param email  - Recipient email address (lowercased before encoding).
 * @param secret - Shared signing secret (e.g. `env.MAGIC_LINK_SECRET`).
 * @param ttlMs  - Token lifetime in milliseconds (default {@link MAGIC_LINK_TTL}).
 * @returns A URL-safe token string: `<payload>.<signature>`.
 *
 * @example
 * ```ts
 * const token = await generateMagicToken('a@b.com', 's3cret');
 * // Use in email link: https://example.com/verify?token={token}
 * ```
 */
export async function generateMagicToken(
  email: string,
  secret: string,
  ttlMs: number = MAGIC_LINK_TTL,
): Promise<string> {
  const expiry = Date.now() + ttlMs;
  const payload = `${email.toLowerCase()}|${expiry}`;
  const payloadEncoded = base64UrlEncode(payload);
  const signature = await hmacSha256(secret, payload);
  const sigEncoded = base64UrlEncode(signature);
  return `${payloadEncoded}.${sigEncoded}`;
}

/**
 * Verify an HMAC-signed magic link token.
 *
 * Validates the HMAC signature, decodes the embedded email and expiry, and
 * checks that the token has not expired.
 *
 * @param token  - The token string (generated by {@link generateMagicToken}).
 * @param secret - The same shared secret used at generation time.
 * @returns The verified email address, or `null` if the token is invalid,
 *          tampered, or expired.
 *
 * @example
 * ```ts
 * const email = await verifyMagicToken(token, 's3cret');
 * if (!email) throw new Error('Invalid or expired link');
 * ```
 */
export async function verifyMagicToken(token: string, secret: string): Promise<string | null> {
  const dotIndex = token.lastIndexOf('.');
  if (dotIndex === -1) return null;

  const payloadEncoded = token.slice(0, dotIndex);
  const sigEncoded = token.slice(dotIndex + 1);

  if (!payloadEncoded || !sigEncoded) return null;

  // Decode payload to recover email + expiry
  const decoded = base64UrlDecode(payloadEncoded);
  if (!decoded) return null;

  const pipeIndex = decoded.lastIndexOf('|');
  if (pipeIndex === -1) return null;

  const email = decoded.slice(0, pipeIndex);
  const expiryStr = decoded.slice(pipeIndex + 1);

  if (!email || !expiryStr) return null;

  const expiry = Number(expiryStr);
  if (!Number.isFinite(expiry)) return null;

  // Verify signature by re-computing HMAC and comparing
  const originalSig = base64UrlDecode(sigEncoded);
  if (!originalSig) return null;

  const expectedSig = await hmacSha256(secret, decoded);

  // Constant-time comparison
  if (!timingSafeEqual(originalSig, expectedSig)) return null;

  // Check expiry
  if (Date.now() > expiry) return null;

  return email;
}
