/**
 * @module services/team_invite
 * @description HMAC-signed invite tokens for team membership.
 * Pure functions — no env, no D1, no side effects.
 *
 * Token format: `base64url(JSON payload) . base64url(HMAC-SHA256(base64url(payload), key))`
 *
 * Payload fields: `{ orgId, email, role, exp }` where `exp` is Unix ms.
 * Default expiry: 7 days from generation.
 */

const EXPIRY_MS = 7 * 24 * 60 * 60 * 1000; // 7 days

export interface InvitePayload {
  orgId: string;
  email: string;
  role: string;
  exp: number;
}

export interface InviteResult {
  token: string;
  expiresAt: string; // ISO 8601
}

/**
 * Generates an HMAC-signed invite token for adding a team member.
 *
 * @param orgId - The organization ID the invite is for
 * @param email - The email address of the invitee
 * @param role - The role to assign (e.g. 'member', 'admin')
 * @param hmacKey - Base64-encoded HMAC-SHA256 key (32+ bytes recommended)
 * @returns An object with the signed token and expiration timestamp
 *
 * @example
 * ```ts
 * const { token, expiresAt } = await generateInvite(
 *   'org_abc123',
 *   'colleague@example.com',
 *   'member',
 *   hmacKey,
 * );
 * // token = "eyJvcmdJZCI6Im9yZ19hYmMxMjMiLCJlbWFpbCI6ImNvbGxlYWd1ZUBleGFtcGxlLmNvbSIsInJvbGUiOiJtZW1iZXIiLCJleHAiOjE3NTE2ODAwMDAwMDB9.WHnOiDmZr5..."
 * ```
 *
 * @throws {InviteTokenError} when the key is empty
 */
export async function generateInvite(
  orgId: string,
  email: string,
  role: string,
  hmacKey: string,
): Promise<InviteResult> {
  if (!hmacKey) throw new InviteTokenError('HMAC key must not be empty');

  const exp = Date.now() + EXPIRY_MS;
  const payload: InvitePayload = { orgId, email, role, exp };
  const payloadB64 = encodeBase64Url(JSON.stringify(payload));
  const sig = await hmacSign(payloadB64, hmacKey);
  return {
    token: `${payloadB64}.${sig}`,
    expiresAt: new Date(exp).toISOString(),
  };
}

/**
 * Validates an invite token and returns the decoded payload.
 *
 * @param token - The invite token to validate (generated by {@link generateInvite})
 * @param hmacKey - Base64-encoded HMAC-SHA256 key (must match the key used at generation)
 * @returns The decoded {@link InvitePayload}
 *
 * @example
 * ```ts
 * const payload = await validateInvite(token, hmacKey);
 * // { orgId: 'org_abc123', email: 'colleague@example.com', role: 'member', exp: 1751680000000 }
 * ```
 *
 * @throws {InviteTokenError} if the token is malformed, tampered, or expired
 */
export async function validateInvite(
  token: string,
  hmacKey: string,
): Promise<InvitePayload> {
  const parts = token.split('.');
  if (parts.length !== 2) throw new InviteTokenError('Malformed invite token');

  const [payloadB64, sig] = parts as [string, string];
  if (!payloadB64 || !sig) throw new InviteTokenError('Malformed invite token');

  // Verify HMAC signature
  const expectedSig = await hmacSign(payloadB64, hmacKey);
  if (!timingSafeEqual(sig, expectedSig)) {
    throw new InviteTokenError('Invalid invite token signature');
  }

  // Decode and validate payload
  let payload: InvitePayload;
  try {
    const decoded = decodeBase64Url(payloadB64);
    payload = JSON.parse(decoded);
  } catch {
    throw new InviteTokenError('Invalid invite token payload encoding');
  }

  // Validate required fields
  if (!payload.orgId || !payload.email || !payload.role || typeof payload.exp !== 'number') {
    throw new InviteTokenError('Invalid invite token payload structure');
  }

  if (payload.exp < Date.now()) {
    throw new InviteTokenError('Invite token has expired');
  }

  return payload;
}

/**
 * Accepts an invite token by validating it and returning the payload
 * for the caller to act on (e.g. create a membership record).
 *
 * @param token - The invite token to accept
 * @param _userId - The accepting user's ID (reserved for future use)
 * @param hmacKey - Base64-encoded HMAC-SHA256 key
 * @returns The validated {@link InvitePayload}
 *
 * @example
 * ```ts
 * const { orgId, role } = await acceptInvite(token, 'user_456', hmacKey);
 * // Caller uses orgId + role to create the membership
 * ```
 *
 * @throws {InviteTokenError} on invalid, tampered, or expired tokens
 */
export async function acceptInvite(
  token: string,
  _userId: string,
  hmacKey: string,
): Promise<InvitePayload> {
  return validateInvite(token, hmacKey);
}

// ── Internal helpers ─────────────────────────────────────────────────

/**
 * Typed error for invite-token operations.
 *
 * @remarks Use `instanceof InviteTokenError` to distinguish invite-specific
 * failures from general errors in callers.
 */
export class InviteTokenError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'InviteTokenError';
  }
}

/**
 * Compute HMAC-SHA256 of a message using a base64-encoded key.
 */
async function hmacSign(message: string, hmacKey: string): Promise<string> {
  const rawKey = Uint8Array.from(atob(hmacKey), (c) => c.charCodeAt(0));
  const key = await crypto.subtle.importKey(
    'raw',
    rawKey,
    { name: 'HMAC', hash: 'SHA-256' },
    false,
    ['sign'],
  );
  const sig = await crypto.subtle.sign(
    'HMAC',
    key,
    new TextEncoder().encode(message),
  );
  return encodeBase64Url(new Uint8Array(sig));
}

/**
 * Base64url-encode a string or byte array (RFC 4648 §5).
 */
function encodeBase64Url(input: string | Uint8Array): string {
  const bytes = typeof input === 'string' ? new TextEncoder().encode(input) : input;
  return btoa(String.fromCharCode(...bytes))
    .replace(/\+/g, '-')
    .replace(/\//g, '_')
    .replace(/=+$/, '');
}

/**
 * Decode a base64url-encoded string back to UTF-8.
 */
function decodeBase64Url(input: string): string {
  const base64 = input.replace(/-/g, '+').replace(/_/g, '/');
  const pad = (4 - (base64.length % 4)) % 4;
  const padded = base64.padEnd(base64.length + pad, '=');
  return new TextDecoder().decode(
    Uint8Array.from(atob(padded), (c) => c.charCodeAt(0)),
  );
}

/**
 * Constant-time string comparison to prevent timing attacks on HMAC verification.
 */
function timingSafeEqual(a: string, b: string): boolean {
  let result = a.length ^ b.length;
  const maxLen = Math.max(a.length, b.length);
  for (let i = 0; i < maxLen; i++) {
    result |= (a.charCodeAt(i) ?? 0) ^ (b.charCodeAt(i) ?? 0);
  }
  return result === 0;
}
