app = "projectsites-clickhouse"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[mounts]
  source = "clickhouse_data"
  destination = "/var/lib/clickhouse"

[env]
  CLICKHOUSE_USER = "dittofeed"
  CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT = "1"

[experimental]
  auto_rollback = true

[[vm]]
  size = "shared-cpu-2x"
  memory = "4096mb"

[[services]]
  internal_port = 8123
  protocol = "tcp"

  [[services.ports]]
    port = 8123
    handlers = ["http"]

  [[services.http_checks]]
    interval = "15s"
    timeout = "5s"
    method = "GET"
    path = "/ping"

[[services]]
  internal_port = 9000
  protocol = "tcp"

  [[services.ports]]
    port = 9000
