import { defineFeatureManifest } from '@projectsites/feature-manifests';
export default defineFeatureManifest({
  slug: 'page_audio_summary',
  name: 'Page Audio Summary',
  description: 'Generates per-route TTS audio summaries via media service and stores MP3 files in R2 for visitor playback.',
  lifecycle: 'alpha',
  flagKey: 'page_audio_summary',
  owner: 'brian@megabyte.space',
  createdAt: '2026-06-17',
  updatedAt: '2026-06-17',
  routes: [],
  apiRoutes: ['POST /api/audio-summary/:siteId', 'GET /api/audio-summary/:siteId'],
  permissions: ['site:read', 'site:write'],
  dependencies: [],
  e2eTests: [],
  unitTests: ['../libs/features/page_audio_summary/__tests__/page_audio_summary.test.ts'],
  integrationTests: [],
  testStatus: 'partial',
  zodSchemas: ['schemas.ts'],
  observability: { axiom: true, logs: true, analytics: false },
  rollout: { defaultEnabled: false, environments: { development: true }, notes: 'Disabled by default. Requires ElevenLabs or OpenAI TTS configured.' },
  risks: ['TTS generation costs tokens. Failing gracefully when TTS provider is unconfigured is required.'],
  removalNotes: 'Drop /api/audio-summary routes and delete R2 objects under audio-summary/{siteId}/.',
});
