[program:onyx_api_server]
command=/bin/sh -c "alembic upgrade head && uvicorn onyx.main:app --host 127.0.0.1 --port 8081"
directory=/app
priority=5
autostart=true
autorestart=true
startsecs=0
stopasgroup=true
stdout_logfile=/var/log/onyx/api_server.log
stdout_logfile_maxbytes=16MB
redirect_stderr=true

[program:onyx_nginx]
command=/usr/sbin/nginx -g "daemon off;"
priority=1
autostart=true
autorestart=true
startsecs=1
stopasgroup=true
stdout_logfile=/var/log/onyx/nginx.log
stdout_logfile_maxbytes=16MB
redirect_stderr=true

[program:onyx_web_server]
command=node server.js
directory=/app/web
priority=10
autostart=true
autorestart=true
startsecs=5
stopasgroup=true
stdout_logfile=/var/log/onyx/web_server.log
stdout_logfile_maxbytes=16MB
redirect_stderr=true
environment=NODE_OPTIONS="--max-old-space-size=4096"

[program:onyx_mcp_server]
command=/usr/local/bin/python -m onyx.mcp_server_main
directory=/app
priority=15
autostart=true
autorestart=true
startsecs=5
stopasgroup=true
stdout_logfile=/var/log/onyx/mcp_server.log
stdout_logfile_maxbytes=16MB
redirect_stderr=true
