log:
  stdout: true
  level: info

persistence:
  defaultStore: default
  visibilityStore: visibility
  numHistoryShards: 4
  datastores:
    default:
      sql:
        pluginName: postgres
        databaseName: projectsites_temporal
        connectAddr: "PLACEHOLDER_HOST:5432"
        connectProtocol: tcp
        user: "PLACEHOLDER_USER"
        password: "PLACEHOLDER_PASSWORD"
        maxConns: 20
        maxIdleConns: 20
        tls:
          enabled: true
          enableHostVerification: false
    visibility:
      sql:
        pluginName: postgres
        databaseName: projectsites_temporal_visibility
        connectAddr: "PLACEHOLDER_HOST:5432"
        connectProtocol: tcp
        user: "PLACEHOLDER_USER"
        password: "PLACEHOLDER_PASSWORD"
        maxConns: 10
        maxIdleConns: 10
        tls:
          enabled: true
          enableHostVerification: false

global:
  membership:
    maxJoinDuration: 30s
    broadcastAddress: "127.0.0.1"

services:
  frontend:
    rpc:
      grpcPort: 7233
      bindOnLocalHost: false
      bindOnIP: "0.0.0.0"
  matching:
    rpc:
      grpcPort: 7235
      bindOnLocalHost: false
      bindOnIP: "0.0.0.0"
  history:
    rpc:
      grpcPort: 7234
      bindOnLocalHost: false
      bindOnIP: "0.0.0.0"
  worker:
    rpc:
      grpcPort: 7239
      bindOnLocalHost: false
      bindOnIP: "0.0.0.0"

clusterMetadata:
  enableGlobalNamespace: false
  failoverVersionIncrement: 100
  masterClusterName: "active"
  currentClusterName: "active"
  clusterInformation:
    active:
      enabled: true
      initialFailoverVersion: 1
      rpcName: "frontend"
      rpcAddress: "127.0.0.1:7233"
