FROM dittofeed/dittofeed-lite:v0.24.0-alpha.17
ENV DEPLOY_V4=2026-06-29T01-20-00Z
ENTRYPOINT ["node", "--max-old-space-size=824", "./packages/lite/dist/scripts/startLite.js", "--workspace-name=ProjectSites"]
