import { defineFeatureManifest } from '@projectsites/feature-manifests';
export default defineFeatureManifest({
  slug: 'edge_personalization',
  name: 'Edge Personalization',
  description: 'Rules-based visitor variant selection using geo, device, referrer, time, and return-visitor signals without storing PII.',
  lifecycle: 'alpha',
  flagKey: 'edge_personalization',
  owner: 'brian@megabyte.space',
  createdAt: '2026-06-17',
  updatedAt: '2026-06-17',
  routes: [],
  apiRoutes: ['POST /api/personalize/:siteId/variants', 'GET /api/personalize/:siteId/resolve'],
  permissions: ['site:read', 'site:write'],
  dependencies: [],
  e2eTests: [],
  unitTests: ['../libs/features/edge_personalization/__tests__/edge_personalization.test.ts'],
  integrationTests: [],
  testStatus: 'partial',
  zodSchemas: ['schemas.ts'],
  observability: { sentry: false, logs: true, analytics: true },
  rollout: { defaultEnabled: false, environments: { development: true }, notes: 'Privacy-safe: no PII stored in signals.' },
  risks: ['Variant rules stored in D1; empty rule set falls back to default variant.'],
  removalNotes: 'Drop /api/personalize routes, remove site_personalization_variants table rows for the site.',
});
