/**
 * @module libs/features/reputation/service
 * @description Business logic for the Reputation suite (ideas #10, #11, #13).
 *
 * Three independent capabilities sharing one module:
 *   - {@link sendReviewRequest}     #10 — LLM-personalized review ask over email/SMS
 *   - {@link draftReviewReply}      #11 — on-brand AI reply draft to a review
 *   - {@link getReputationSnapshot} #13 — cross-platform rating aggregate + flag
 *
 * @packageDocumentation
 */

import type { Env } from '../../../src/types/env.js';
import { dbInsert, dbQuery, dbQueryOne } from '../../../src/services/db.js';
import { callExternalLLM } from '../../../src/services/external_llm.js';
import { lookupBusiness } from '../../../src/services/google_places.js';
import { sendSms } from '../../../src/services/twilio.js';
import {
  ReviewRequestSchema,
  ReviewReplyDraftSchema,
  ReputationSnapshotSchema,
  type ReviewRequest,
  type ReviewRequestChannel,
  type ReviewReplyDraft,
  type ReputationSnapshot,
  type ReputationPlatform,
  type PlatformSnapshot,
  type CachedReview,
} from './schemas.js';

/** Flag keys gating each capability in this module. */
export const FLAG_REVIEW_REQUESTS = 'review_requests';
export const FLAG_REVIEW_RESPONDER = 'review_responder';
export const FLAG_REPUTATION_MONITOR = 'reputation_monitor';

/** BrightLocal trust thresholds — below either flips `needsAttention`. */
const MIN_AVG_RATING = 4.5;
const MIN_REVIEW_COUNT = 20;

/** Cap on recent reviews surfaced in a snapshot. */
const RECENT_REVIEW_CAP = 10;

/** Minimal site row used to personalize asks + resolve the review link. */
interface SiteRow {
  id: string;
  org_id: string | null;
  business_name: string;
  google_place_id: string | null;
}

/** Structured log line carrying the feature slug for per-feature filtering. */
function logLine(message: string, extra: Record<string, unknown>): void {
  console.warn(
    JSON.stringify({ level: 'info', service: 'reputation', feature_slug: 'reputation', message, ...extra }),
  );
}

/** Load the minimal site context, or null when absent. */
async function loadSite(env: Env, siteId: string): Promise<SiteRow | null> {
  return dbQueryOne<SiteRow>(
    env.DB,
    'SELECT id, org_id, business_name, google_place_id FROM sites WHERE id = ? AND deleted_at IS NULL LIMIT 1',
    [siteId],
  ).catch(() => null);
}

/** Build a Google "write a review" deep-link for a place, or a search fallback. */
function googleReviewLink(placeId: string | null, businessName: string): string {
  if (placeId) {
    return `https://search.google.com/local/writereview?placeid=${encodeURIComponent(placeId)}`;
  }
  return `https://www.google.com/search?q=${encodeURIComponent(`${businessName} reviews`)}`;
}

// ─── #10 — AI review-request engine ─────────────────────────────────────────

/** Input for {@link sendReviewRequest}. */
export interface SendReviewRequestInput {
  siteId: string;
  channel: ReviewRequestChannel;
  /** Email address (channel `email`) or E.164 phone (channel `sms`). */
  recipient: string;
  /** Optional context about the job/visit to personalize the ask. */
  jobContext?: string;
}

/**
 * Send an LLM-personalized review request over email or SMS and log it to D1.
 *
 * The ask is generated by the LLM (best-effort; falls back to a templated
 * message on failure), embeds the Google review deep-link, and is delivered via
 * Resend (email) or Twilio {@link sendSms} (SMS). Every send — success or
 * failure — is persisted to `review_requests`.
 *
 * @param env   - Worker env (DB, RESEND_API_KEY, Twilio creds).
 * @param input - Site, channel, recipient, optional job context.
 * @returns The persisted {@link ReviewRequest} record (status `sent` | `failed`).
 * @throws Never — delivery failures are captured in the returned record's status.
 *
 * @example
 * ```ts
 * const req = await sendReviewRequest(env, {
 *   siteId, channel: 'sms', recipient: '+19735551234', jobContext: 'Haircut + beard trim',
 * });
 * ```
 */
export async function sendReviewRequest(env: Env, input: SendReviewRequestInput): Promise<ReviewRequest> {
  const site = await loadSite(env, input.siteId);
  const businessName = site?.business_name ?? 'our business';
  const link = googleReviewLink(site?.google_place_id ?? null, businessName);

  const message = await personalizeAsk(env, businessName, input.channel, link, input.jobContext);

  let status: ReviewRequest['status'] = 'sent';
  try {
    if (input.channel === 'email') {
      await sendReviewEmail(env, input.recipient, businessName, message);
    } else {
      await sendReviewText(env, input.siteId, input.recipient, message);
    }
  } catch (err) {
    status = 'failed';
    logLine('review_request_delivery_failed', {
      site_id: input.siteId,
      channel: input.channel,
      error: err instanceof Error ? err.message : String(err),
    });
  }

  const record: ReviewRequest = ReviewRequestSchema.parse({
    id: crypto.randomUUID(),
    siteId: input.siteId,
    orgId: site?.org_id ?? null,
    channel: input.channel,
    recipient: input.recipient,
    message,
    link,
    status,
    createdAt: new Date().toISOString(),
  });

  await dbInsert(env.DB, 'review_requests', {
    id: record.id,
    org_id: record.orgId,
    site_id: record.siteId,
    channel: record.channel,
    recipient: record.recipient,
    message: record.message,
    link: record.link,
    status: record.status,
  }).catch((err) =>
    logLine('review_request_persist_failed', { site_id: input.siteId, error: String(err) }),
  );

  logLine('review_request', { site_id: input.siteId, channel: input.channel, status });
  return record;
}

/** Generate a short personalized ask; falls back to a template on LLM failure. */
async function personalizeAsk(
  env: Env,
  businessName: string,
  channel: ReviewRequestChannel,
  link: string,
  jobContext?: string,
): Promise<string> {
  const limit = channel === 'sms' ? '320 characters (2 SMS segments)' : '90 words';
  const fallback =
    channel === 'sms'
      ? `Thanks for choosing ${businessName}! A quick Google review would mean a lot: ${link}`
      : `Hi! Thanks for choosing ${businessName}. If you have a moment, we'd be grateful for a quick Google review — it helps neighbors find us: ${link}`;

  try {
    const res = await callExternalLLM(env, {
      system:
        'You write warm, concise, non-pushy review-request messages for a local business. ' +
        'Never fabricate details. Always include the exact review link provided, unedited. ' +
        `Keep it under ${limit}. Output only the message text — no preamble, no quotes.`,
      user:
        `Business: ${businessName}\n` +
        `Channel: ${channel}\n` +
        (jobContext ? `Recent job/visit: ${jobContext}\n` : '') +
        `Review link (include verbatim): ${link}`,
      temperature: 0.7,
      maxTokens: 220,
      model: 'gpt-4o-mini',
    });
    const text = res.output?.trim();
    if (!text) return fallback;
    return text.includes(link) ? text : `${text} ${link}`;
  } catch (err) {
    logLine('review_request_llm_fallback', { error: err instanceof Error ? err.message : String(err) });
    return fallback;
  }
}

/** Deliver the review-request email via Resend (mirrors notifications.ts pattern). */
async function sendReviewEmail(env: Env, to: string, businessName: string, message: string): Promise<void> {
  if (!env.RESEND_API_KEY) throw new Error('Email delivery is not configured');
  const html = `<div style="font-family:system-ui,sans-serif;font-size:15px;line-height:1.5">${escapeHtml(
    message,
  ).replace(/\n/g, '<br>')}</div>`;
  const res = await fetch('https://api.resend.com/emails', {
    method: 'POST',
    headers: { Authorization: `Bearer ${env.RESEND_API_KEY}`, 'Content-Type': 'application/json' },
    body: JSON.stringify({
      from: `${businessName} <noreply@projectsites.dev>`,
      to,
      subject: `How was your experience with ${businessName}?`,
      html,
    }),
  });
  if (!res.ok) throw new Error(`Resend review-request send failed: ${res.status}`);
}

/** Deliver the review-request SMS from the site's active Twilio number. */
async function sendReviewText(env: Env, siteId: string, to: string, message: string): Promise<void> {
  const num = await dbQueryOne<{ phone_number: string }>(
    env.DB,
    "SELECT phone_number FROM voice_numbers WHERE site_id = ? AND status = 'active' AND deleted_at IS NULL LIMIT 1",
    [siteId],
  ).catch(() => null);
  if (!num?.phone_number) throw new Error('No active SMS number provisioned for this site');
  await sendSms(env, { from: num.phone_number, to, body: message });
}

/** Minimal HTML escape for interpolated message bodies. */
function escapeHtml(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

// ─── #11 — AI review responder ──────────────────────────────────────────────

/** Input for {@link draftReviewReply}. */
export interface DraftReviewReplyInput {
  siteId: string;
  reviewText: string;
  rating: number;
  /** Reply tone (defaults to "warm and professional"). */
  tone?: string;
}

/**
 * Draft an on-brand reply to a customer review via the LLM.
 *
 * Best-effort spend is recorded against the `token_burn_meter` feature when
 * that module is present (dynamic import — never a hard dependency). The draft
 * is for human review; it is never auto-published.
 *
 * @param env   - Worker env (DB, LLM keys).
 * @param input - Site, review text, rating, optional tone.
 * @returns A {@link ReviewReplyDraft}. `aiModel` is null when generation failed.
 *
 * @example
 * ```ts
 * const draft = await draftReviewReply(env, { siteId, reviewText: 'Great cut!', rating: 5 });
 * ```
 */
export async function draftReviewReply(env: Env, input: DraftReviewReplyInput): Promise<ReviewReplyDraft> {
  const site = await loadSite(env, input.siteId);
  const businessName = site?.business_name ?? 'our business';
  const tone = input.tone?.trim() || 'warm and professional';

  let draft = '';
  let aiModel: string | null = null;
  try {
    const res = await callExternalLLM(env, {
      system:
        `You are the owner of "${businessName}" replying publicly to a customer review. ` +
        `Write a ${tone} reply. Thank specifics, address concerns honestly, never argue, never offer ` +
        'compensation, never invent facts. Under 80 words. Output only the reply text.',
      user: `Rating: ${input.rating}/5\nReview: ${input.reviewText}`,
      temperature: 0.7,
      maxTokens: 240,
      model: 'gpt-4o-mini',
    });
    draft = res.output?.trim() ?? '';
    aiModel = res.model_used;
    await recordReplySpend(env, site?.org_id ?? null, input.siteId, res);
  } catch (err) {
    logLine('review_reply_llm_failed', {
      site_id: input.siteId,
      error: err instanceof Error ? err.message : String(err),
    });
  }

  if (!draft) {
    draft =
      input.rating >= 4
        ? `Thank you so much for the kind words about ${businessName} — we truly appreciate you and hope to see you again soon!`
        : `Thank you for the honest feedback. We're sorry your experience at ${businessName} fell short — please reach out so we can make it right.`;
  }

  logLine('review_reply_draft', { site_id: input.siteId, ai_model: aiModel, rating: input.rating });
  return ReviewReplyDraftSchema.parse({
    siteId: input.siteId,
    reviewText: input.reviewText,
    rating: input.rating,
    tone,
    draft,
    aiModel,
  });
}

/** Best-effort spend recording via the token_burn_meter module, if present. */
async function recordReplySpend(
  env: Env,
  orgId: string | null,
  siteId: string,
  res: { model_used: string; token_count: number; cost_estimate: number },
): Promise<void> {
  if (!orgId) return;
  try {
    const mod = await import('../token_burn_meter/service.js');
    await mod.recordSpend(env, orgId, {
      tokensIn: 0,
      tokensOut: res.token_count ?? 0,
      model: res.model_used || 'unknown',
      usd: res.cost_estimate ?? 0,
      siteId,
    });
  } catch {
    // token_burn_meter absent or spend rejected — non-fatal.
  }
}

// ─── #13 — multi-platform reputation monitor ────────────────────────────────

/**
 * Aggregate a site's reputation across platforms.
 *
 * Google is live-fetched via {@link lookupBusiness}; other platforms read
 * cached rows (`reputation_platforms` for ratings, `reputation_reviews_cache`
 * for recent reviews) that an external sync must populate. Flags
 * `needsAttention` when the weighted average drops below 4.5 OR the total
 * review count is under 20 (BrightLocal thresholds).
 *
 * @param env    - Worker env (DB, GOOGLE_PLACES_API_KEY).
 * @param siteId - Site to snapshot.
 * @returns A {@link ReputationSnapshot}.
 *
 * @example
 * ```ts
 * const snap = await getReputationSnapshot(env, siteId);
 * if (snap.needsAttention) notifyOwner(snap);
 * ```
 */
export async function getReputationSnapshot(env: Env, siteId: string): Promise<ReputationSnapshot> {
  const site = await loadSite(env, siteId);
  const platforms: PlatformSnapshot[] = [];
  const recent: CachedReview[] = [];

  // --- Google (live) ---
  if (site) {
    const places = await lookupBusiness(env.GOOGLE_PLACES_API_KEY, site.business_name, '').catch(() => null);
    if (places && places.rating != null && places.review_count != null) {
      platforms.push({ platform: 'google', rating: places.rating, reviewCount: places.review_count });
      for (const r of places.reviews ?? []) {
        recent.push({ platform: 'google', text: r.text, author: r.author, rating: r.rating, time: r.time });
      }
    }
  }

  // --- Other platforms (cached ratings) ---
  const { data: rows } = await dbQuery<{ platform: string; rating: number | null; review_count: number | null }>(
    env.DB,
    "SELECT platform, rating, review_count FROM reputation_platforms WHERE site_id = ? AND platform != 'google' AND deleted_at IS NULL",
    [siteId],
  ).catch(() => ({ data: [] as { platform: string; rating: number | null; review_count: number | null }[] }));
  for (const row of rows) {
    if (row.rating == null || row.review_count == null) continue;
    platforms.push({
      platform: row.platform as ReputationPlatform,
      rating: row.rating,
      reviewCount: row.review_count,
    });
  }

  // --- Cached recent reviews (all non-Google platforms) ---
  const { data: cached } = await dbQuery<{
    platform: string;
    text: string;
    author: string;
    rating: number;
    review_time: string;
  }>(
    env.DB,
    'SELECT platform, text, author, rating, review_time FROM reputation_reviews_cache WHERE site_id = ? AND deleted_at IS NULL ORDER BY created_at DESC LIMIT ?',
    [siteId, RECENT_REVIEW_CAP],
  ).catch(() => ({
    data: [] as { platform: string; text: string; author: string; rating: number; review_time: string }[],
  }));
  for (const r of cached) {
    recent.push({ platform: r.platform as ReputationPlatform, text: r.text, author: r.author, rating: r.rating, time: r.review_time });
  }

  const totalReviews = platforms.reduce((sum, p) => sum + p.reviewCount, 0);
  const weighted = platforms.reduce((sum, p) => sum + p.rating * p.reviewCount, 0);
  const averageRating = totalReviews > 0 ? Number((weighted / totalReviews).toFixed(2)) : 0;
  const needsAttention = totalReviews < MIN_REVIEW_COUNT || (totalReviews > 0 && averageRating < MIN_AVG_RATING);

  logLine('reputation_snapshot', {
    site_id: siteId,
    platforms: platforms.length,
    total_reviews: totalReviews,
    average_rating: averageRating,
    needs_attention: needsAttention,
  });

  return ReputationSnapshotSchema.parse({
    siteId,
    averageRating,
    totalReviews,
    platforms,
    recent: recent.slice(0, RECENT_REVIEW_CAP),
    needsAttention,
  });
}
