app = "projectsites-unkey"
primary_region = "ewr"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 7070
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 2048

[env]
  UNKEY_HTTP_PORT = "7070"
  UNKEY_DATABASE_PRIMARY = "2wNKbL89szJozW9.root:L2rAhARgfwUoU9JounJ4HaUqw0Dy@tcp(gateway01.eu-central-1.prod.aws.tidbcloud.com:4000)/unkey?parseTime=true&tls=true"
  UNKEY_REDIS_URL = "rediss://default:gQAAAAAAAs0dAAIgcDIwYmJiODBjYmM3MzA0MTA2OTM5ZWM0MjZjNTI0ZTc3ZA@rapid-hog-183581.upstash.io:6379"
  UNKEY_ROOT_KEY = "cc95d65cedec93aaa033f2065dccb559230e6b7fc7dfb7380c7c75c5958fa962"
