import { defineFeatureManifest } from '@projectsites/feature-manifests';
export default defineFeatureManifest({
  slug: 'ai_concierge_widget',
  name: 'AI Concierge Widget',
  description: 'Per-site AI chat widget that grounds responses via semantic RAG search and Workers AI LLM to answer visitor questions about site content.',
  lifecycle: 'alpha',
  flagKey: 'ai_concierge_widget',
  owner: 'brian@megabyte.space',
  createdAt: '2026-06-17',
  updatedAt: '2026-06-17',
  routes: [],
  apiRoutes: ['POST /api/concierge/:siteId/message', 'GET /api/concierge/:siteId/config'],
  permissions: ['site:read'],
  dependencies: ['site_semantic_search'],
  e2eTests: [],
  unitTests: ['../libs/features/ai_concierge_widget/__tests__/ai_concierge_widget.test.ts'],
  integrationTests: [],
  testStatus: 'partial',
  zodSchemas: ['schemas.ts'],
  observability: { axiom: true, logs: true, analytics: false },
  rollout: { defaultEnabled: false, environments: { development: true }, notes: 'Disabled by default; enable per-org via feature flag admin.' },
  risks: ['LLM responses may be inaccurate; always ground via RAG before answering.'],
  removalNotes: 'Drop /api/concierge routes and the flag row. No persistent state beyond KV config cache.',
});
