/**
 * @module routes/changelog_public
 * @description Build-in-public public changelog (feature #35).
 *
 * Reads `marketing/changelog/CHANGELOG.md` from R2 and serves:
 *  - `GET /changelog`        — rendered HTML (minimal shell + markdown)
 *  - `GET /changelog.rss`    — RSS 2.0 feed parsed from conventional-commits sections
 *  - `GET /changelog.json`   — JSON array (one entry per release)
 *
 * The changelog is regenerated by a cron task from conventional commits via the
 * existing changelog-generator agent. Each publish fires a Listmonk webhook so
 * newsletter subscribers receive the update. The Listmonk URL is read from
 * `env.LISTMONK_WEBHOOK_URL` (optional — silently skipped when missing).
 *
 * Flag-gated on `public_changelog`. Returns 404 when flag off.
 *
 * @packageDocumentation
 */

import { Hono } from 'hono';
import type { Env, Variables } from '../types/env.js';
import { isFlagOn } from '../modules/feature_flags/services.js';

const changelog = new Hono<{ Bindings: Env; Variables: Variables }>();

const CHANGELOG_R2_KEY = 'marketing/changelog/CHANGELOG.md';
const SITE_BASE_URL = 'https://projectsites.dev';

interface ChangelogEntry {
  version: string;
  date: string;
  raw: string;
  html: string;
}

async function readChangelog(env: Env): Promise<string | null> {
  const obj = await env.SITES_BUCKET.get(CHANGELOG_R2_KEY);
  if (!obj) return null;
  return obj.text();
}

/**
 * Split a CHANGELOG.md (Keep-A-Changelog flavored) into entries.
 * Each entry begins at a `## [<version>] - <YYYY-MM-DD>` header.
 */
function parseEntries(markdown: string): ChangelogEntry[] {
  const out: ChangelogEntry[] = [];
  const lines = markdown.split('\n');
  let current: ChangelogEntry | null = null;
  const headerRe = /^##\s+\[?([^\]]+?)\]?(?:\s+-\s+(\d{4}-\d{2}-\d{2}))?\s*$/;
  for (const line of lines) {
    const match = line.match(headerRe);
    if (match) {
      if (current) out.push(finalizeEntry(current));
      current = {
        version: match[1].trim(),
        date: match[2] ?? new Date().toISOString().slice(0, 10),
        raw: '',
        html: '',
      };
      continue;
    }
    if (current) current.raw += `${line}\n`;
  }
  if (current) out.push(finalizeEntry(current));
  return out;
}

function finalizeEntry(entry: ChangelogEntry): ChangelogEntry {
  entry.html = renderMarkdown(entry.raw.trim());
  return entry;
}

/**
 * Minimal markdown → HTML. Keeps deps zero (Worker bundle stays small).
 * Handles headers, lists, bold/italic, inline code, links.
 */
function renderMarkdown(md: string): string {
  // Escape HTML first
  let out = md.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
  // Headers
  out = out
    .replace(/^### (.+)$/gm, '<h3>$1</h3>')
    .replace(/^## (.+)$/gm, '<h2>$1</h2>')
    .replace(/^# (.+)$/gm, '<h1>$1</h1>');
  // Bold / italic / code
  out = out
    .replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>')
    .replace(/`([^`]+)`/g, '<code>$1</code>');
  // Lists
  out = out.replace(/^(?:- |\* )(.+)$/gm, '<li>$1</li>');
  out = out.replace(/(<li>[\s\S]+?<\/li>)/g, '<ul>$1</ul>');
  // Links
  out = out.replace(/\[([^\]]+)\]\(([^)]+)\)/g, '<a href="$2">$1</a>');
  // Paragraphs
  out = out
    .split(/\n\n+/)
    .map((block) =>
      /^<(h1|h2|h3|ul|ol|li)/.test(block.trim()) ? block : `<p>${block.trim()}</p>`,
    )
    .join('\n');
  return out;
}

function entriesToRss(entries: ChangelogEntry[]): string {
  const items = entries
    .map(
      (e) => `    <item>
      <title>${escapeXml(e.version)}</title>
      <link>${SITE_BASE_URL}/changelog#${escapeXml(e.version)}</link>
      <guid isPermaLink="false">${escapeXml(e.version)}</guid>
      <pubDate>${new Date(e.date).toUTCString()}</pubDate>
      <description><![CDATA[${e.html}]]></description>
    </item>`,
    )
    .join('\n');
  return `<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0">
  <channel>
    <title>projectsites.dev — Changelog</title>
    <link>${SITE_BASE_URL}/changelog</link>
    <description>Build-in-public changelog generated from conventional commits.</description>
    <language>en-us</language>
    <lastBuildDate>${new Date().toUTCString()}</lastBuildDate>
${items}
  </channel>
</rss>`;
}

function escapeXml(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

function entriesToHtml(entries: ChangelogEntry[]): string {
  const body = entries
    .map(
      (e) => `<article id="${escapeXml(e.version)}">
  <header><h2>${escapeXml(e.version)} <small>${escapeXml(e.date)}</small></h2></header>
  ${e.html}
</article>`,
    )
    .join('\n');
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Changelog | projectsites.dev</title>
<meta name="description" content="Public, build-in-public changelog for projectsites.dev — release notes generated from conventional commits.">
<link rel="alternate" type="application/rss+xml" href="/changelog.rss" title="projectsites.dev Changelog">
<meta name="color-scheme" content="dark light">
<style>
  :root{color-scheme:dark light;--bg:#060610;--ink:#f4f4ff;--accent:#00e5ff;font-family:system-ui,sans-serif;}
  body{background:var(--bg);color:var(--ink);max-width:760px;margin:0 auto;padding:48px 24px;line-height:1.6;}
  h1{font-size:2rem;margin:0 0 .5em;}
  article{padding:24px 0;border-bottom:1px solid rgba(255,255,255,.08);}
  article h2{font-size:1.4rem;color:var(--accent);}
  article small{color:rgba(244,244,255,.5);font-weight:400;font-size:.85rem;margin-left:.5em;}
  a{color:var(--accent);}
  code{background:rgba(0,229,255,.1);padding:2px 6px;border-radius:4px;font-size:.9em;}
  ul{padding-left:1.2em;}
</style>
</head>
<body>
<main>
  <h1>Changelog</h1>
  <p>Public release notes for projectsites.dev. <a href="/changelog.rss">RSS feed</a>.</p>
  ${body}
</main>
</body>
</html>`;
}

// ─── Routes ──────────────────────────────────────────────────────────

changelog.get('/changelog', async (c) => {
  if (!(await isFlagOn(c.env, 'public_changelog'))) {
    return c.notFound();
  }
  const md = await readChangelog(c.env);
  if (!md) return c.text('Changelog not yet published.', 404);
  const entries = parseEntries(md);
  return c.html(entriesToHtml(entries));
});

changelog.get('/changelog.rss', async (c) => {
  if (!(await isFlagOn(c.env, 'public_changelog'))) {
    return c.notFound();
  }
  const md = await readChangelog(c.env);
  if (!md) return c.text('Changelog not yet published.', 404);
  const entries = parseEntries(md);
  return new Response(entriesToRss(entries), {
    headers: { 'content-type': 'application/rss+xml; charset=utf-8' },
  });
});

changelog.get('/changelog.json', async (c) => {
  if (!(await isFlagOn(c.env, 'public_changelog'))) {
    return c.notFound();
  }
  const md = await readChangelog(c.env);
  if (!md) return c.json({ entries: [] });
  const entries = parseEntries(md).map(({ version, date, raw }) => ({
    version,
    date,
    raw,
  }));
  return c.json({ entries });
});

// ─── Webhook helper (called by changelog-publish job) ────────────────

/**
 * Fire a Listmonk webhook when the changelog updates. Best-effort —
 * absent `LISTMONK_WEBHOOK_URL` silently skips. Caller passes the latest
 * entry version + date.
 */
export async function fireListmonkChangelogWebhook(
  env: Env,
  latest: { version: string; date: string; summary: string },
): Promise<{ fired: boolean }> {
  const url = (env as Env & { LISTMONK_WEBHOOK_URL?: string }).LISTMONK_WEBHOOK_URL;
  if (!url) return { fired: false };
  try {
    await fetch(url, {
      method: 'POST',
      headers: { 'content-type': 'application/json' },
      body: JSON.stringify({
        source: 'projectsites_changelog',
        version: latest.version,
        date: latest.date,
        summary: latest.summary,
        url: `${SITE_BASE_URL}/changelog#${encodeURIComponent(latest.version)}`,
      }),
    });
    return { fired: true };
  } catch {
    return { fired: false };
  }
}

// Internal helpers exported for unit tests
export { parseEntries, renderMarkdown, entriesToRss, entriesToHtml };
export { changelog as changelogPublicRoutes };
