app = "projectsites-clickhouse"

[build]
  image = "clickhouse/clickhouse-server:24.12.6.70-alpine"

[[mounts]]
  source = "clickhouse_data"
  destination = "/var/lib/clickhouse"
  size_gb = 50

[env]
  CLICKHOUSE_USER = "dittofeed"
  CLICKHOUSE_PASSWORD = "54e3be7cd78da23d49b90b8c3ca30f61"
  CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT = "1"

[http_service]
  internal_port = 8123
  force_https = false

[[http_service.checks]]
  interval = "15s"
  timeout = "5s"
  method = "GET"
  path = "/ping"
