name = "nango-proxy"
main = "worker.ts"
compatibility_date = "2025-04-01"
account_id = "84fa0d1b16ff8086dd958c468ce7fd59"
routes = [
  { pattern = "nango.projectsites.dev/*", zone_name = "projectsites.dev" },
]
[observability]
enabled = true
