app = "projectsites-maxun-frontend"
primary_region = "ewr"

[build]
  image = "getmaxun/maxun-frontend:latest"

[env]
  FRONTEND_PORT = "5173"

[[services]]
  protocol = "tcp"
  internal_port = 5173

  [[services.ports]]
    port = 80
    handlers = ["http"]
  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1
