[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid
logfile_maxbytes=50MB
loglevel=info

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/nginx-out.log
stderr_logfile=/var/log/supervisor/nginx-err.log
priority=10

[program:backend]
command=/usr/local/bin/docker-entrypoint.sh npm run server
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/backend-out.log
stderr_logfile=/var/log/supervisor/backend-err.log
priority=20
environment=NODE_ENV="production"
