[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid
logfile_maxbytes=50MB
loglevel=info

[program:minio]
command=/usr/local/bin/minio server /data/minio --console-address :9001
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/minio-out.log
stderr_logfile=/var/log/supervisor/minio-err.log
environment=MINIO_ROOT_USER="%(ENV_MINIO_ACCESS_KEY)s",MINIO_ROOT_PASSWORD="%(ENV_MINIO_SECRET_KEY)s"

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/nginx-out.log
stderr_logfile=/var/log/supervisor/nginx-err.log
priority=10

[program:backend]
command=/usr/local/bin/docker-entrypoint.sh npm run server
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/backend-out.log
stderr_logfile=/var/log/supervisor/backend-err.log
priority=20
environment=NODE_ENV="production"
