ALTER TABLE core."apiKey" ADD COLUMN IF NOT EXISTS "id" uuid;
ALTER TABLE core."apiKey" ADD COLUMN IF NOT EXISTS "expiresAt" timestamp with time zone;
ALTER TABLE core."apiKey" ADD COLUMN IF NOT EXISTS "revokedAt" timestamp with time zone;
ALTER TABLE core."apiKey" ADD COLUMN IF NOT EXISTS "createdAt" timestamp with time zone;
ALTER TABLE core."apiKey" ADD COLUMN IF NOT EXISTS "updatedAt" timestamp with time zone;
ALTER TABLE core."appToken" ADD COLUMN IF NOT EXISTS "id" uuid;
ALTER TABLE core."appToken" ADD COLUMN IF NOT EXISTS "workspaceId" uuid;
ALTER TABLE core."appToken" ADD COLUMN IF NOT EXISTS "type" text;
ALTER TABLE core."appToken" ADD COLUMN IF NOT EXISTS "value" text;
ALTER TABLE core."appToken" ADD COLUMN IF NOT EXISTS "expiresAt" timestamp with time zone;
ALTER TABLE core."appToken" ADD COLUMN IF NOT EXISTS "deletedAt" timestamp with time zone;
ALTER TABLE core."appToken" ADD COLUMN IF NOT EXISTS "revokedAt" timestamp with time zone;
ALTER TABLE core."appToken" ADD COLUMN IF NOT EXISTS "createdAt" timestamp with time zone;
ALTER TABLE core."appToken" ADD COLUMN IF NOT EXISTS "updatedAt" timestamp with time zone;
ALTER TABLE core."appToken" ADD COLUMN IF NOT EXISTS "context" jsonb;
ALTER TABLE core."applicationRegistration" ADD COLUMN IF NOT EXISTS "id" uuid;
ALTER TABLE core."applicationRegistration" ADD COLUMN IF NOT EXISTS "universalIdentifier" uuid;
ALTER TABLE core."applicationRegistration" ADD COLUMN IF NOT EXISTS "name" text;
ALTER TABLE core."applicationRegistration" ADD COLUMN IF NOT EXISTS "oAuthClientId" text;
ALTER TABLE core."applicationRegistration" ADD COLUMN IF NOT EXISTS "oAuthClientSecretHash" text;
ALTER TABLE core."applicationRegistration" ADD COLUMN IF NOT EXISTS "oAuthRedirectUris" text;
ALTER TABLE core."applicationRegistration" ADD COLUMN IF NOT EXISTS "oAuthScopes" text;
ALTER TABLE core."applicationRegistration" ADD COLUMN IF NOT EXISTS "createdByUserId" uuid;
ALTER TABLE core."applicationRegistration" ADD COLUMN IF NOT EXISTS "ownerWorkspaceId" uuid;
ALTER TABLE core."applicationRegistration" ADD COLUMN IF NOT EXISTS "sourcePackage" text;
ALTER TABLE core."applicationRegistration" ADD COLUMN IF NOT EXISTS "tarballFileId" uuid;
ALTER TABLE core."applicationRegistration" ADD COLUMN IF NOT EXISTS "latestAvailableVersion" text;
ALTER TABLE core."applicationRegistration" ADD COLUMN IF NOT EXISTS "isListed" boolean;
ALTER TABLE core."applicationRegistration" ADD COLUMN IF NOT EXISTS "isFeatured" boolean;
ALTER TABLE core."applicationRegistration" ADD COLUMN IF NOT EXISTS "isPreInstalled" boolean;
ALTER TABLE core."applicationRegistration" ADD COLUMN IF NOT EXISTS "manifest" jsonb;
ALTER TABLE core."applicationRegistration" ADD COLUMN IF NOT EXISTS "createdAt" timestamp with time zone;
ALTER TABLE core."applicationRegistration" ADD COLUMN IF NOT EXISTS "updatedAt" timestamp with time zone;
ALTER TABLE core."applicationRegistration" ADD COLUMN IF NOT EXISTS "deletedAt" timestamp with time zone;
ALTER TABLE core."applicationRegistrationVariable" ADD COLUMN IF NOT EXISTS "id" uuid;
ALTER TABLE core."applicationRegistrationVariable" ADD COLUMN IF NOT EXISTS "key" text;
ALTER TABLE core."applicationRegistrationVariable" ADD COLUMN IF NOT EXISTS "encryptedValue" text;
ALTER TABLE core."applicationRegistrationVariable" ADD COLUMN IF NOT EXISTS "description" text;
ALTER TABLE core."applicationRegistrationVariable" ADD COLUMN IF NOT EXISTS "isSecret" boolean;
ALTER TABLE core."applicationRegistrationVariable" ADD COLUMN IF NOT EXISTS "isRequired" boolean;
ALTER TABLE core."applicationRegistrationVariable" ADD COLUMN IF NOT EXISTS "applicationRegistrationId" uuid;
ALTER TABLE core."applicationRegistrationVariable" ADD COLUMN IF NOT EXISTS "createdAt" timestamp with time zone;
ALTER TABLE core."applicationRegistrationVariable" ADD COLUMN IF NOT EXISTS "updatedAt" timestamp with time zone;
ALTER TABLE core."applicationVariable" ADD COLUMN IF NOT EXISTS "id" uuid;
ALTER TABLE core."applicationVariable" ADD COLUMN IF NOT EXISTS "key" text;
ALTER TABLE core."applicationVariable" ADD COLUMN IF NOT EXISTS "value" text;
ALTER TABLE core."applicationVariable" ADD COLUMN IF NOT EXISTS "description" text;
ALTER TABLE core."applicationVariable" ADD COLUMN IF NOT EXISTS "isSecret" boolean;
ALTER TABLE core."applicationVariable" ADD COLUMN IF NOT EXISTS "createdAt" timestamp with time zone;
ALTER TABLE core."applicationVariable" ADD COLUMN IF NOT EXISTS "updatedAt" timestamp with time zone;
ALTER TABLE core."application" ADD COLUMN IF NOT EXISTS "id" uuid;
ALTER TABLE core."application" ADD COLUMN IF NOT EXISTS "universalIdentifier" uuid;
ALTER TABLE core."application" ADD COLUMN IF NOT EXISTS "name" text;
ALTER TABLE core."application" ADD COLUMN IF NOT EXISTS "description" text;
ALTER TABLE core."application" ADD COLUMN IF NOT EXISTS "logo" text;
ALTER TABLE core."application" ADD COLUMN IF NOT EXISTS "version" text;
ALTER TABLE core."application" ADD COLUMN IF NOT EXISTS "sourcePath" text;
ALTER TABLE core."application" ADD COLUMN IF NOT EXISTS "packageJsonChecksum" text;
ALTER TABLE core."application" ADD COLUMN IF NOT EXISTS "packageJsonFileId" uuid;
ALTER TABLE core."application" ADD COLUMN IF NOT EXISTS "yarnLockChecksum" text;
ALTER TABLE core."application" ADD COLUMN IF NOT EXISTS "yarnLockFileId" uuid;
ALTER TABLE core."application" ADD COLUMN IF NOT EXISTS "availablePackages" jsonb;
ALTER TABLE core."application" ADD COLUMN IF NOT EXISTS "logicFunctionLayerId" uuid;
ALTER TABLE core."application" ADD COLUMN IF NOT EXISTS "defaultRoleId" uuid;
ALTER TABLE core."application" ADD COLUMN IF NOT EXISTS "settingsCustomTabFrontComponentId" uuid;
ALTER TABLE core."application" ADD COLUMN IF NOT EXISTS "canBeUninstalled" boolean;
ALTER TABLE core."application" ADD COLUMN IF NOT EXISTS "isSdkLayerStale" boolean;
ALTER TABLE core."application" ADD COLUMN IF NOT EXISTS "applicationRegistrationId" uuid;
ALTER TABLE core."application" ADD COLUMN IF NOT EXISTS "primaryPublicDomainId" uuid;
ALTER TABLE core."application" ADD COLUMN IF NOT EXISTS "createdAt" timestamp with time zone;
ALTER TABLE core."application" ADD COLUMN IF NOT EXISTS "updatedAt" timestamp with time zone;
ALTER TABLE core."application" ADD COLUMN IF NOT EXISTS "deletedAt" timestamp with time zone;
ALTER TABLE core."approvedAccessDomain" ADD COLUMN IF NOT EXISTS "id" uuid;
ALTER TABLE core."approvedAccessDomain" ADD COLUMN IF NOT EXISTS "createdAt" timestamp with time zone;
ALTER TABLE core."approvedAccessDomain" ADD COLUMN IF NOT EXISTS "updatedAt" timestamp with time zone;
ALTER TABLE core."approvedAccessDomain" ADD COLUMN IF NOT EXISTS "domain" character varying;
ALTER TABLE core."approvedAccessDomain" ADD COLUMN IF NOT EXISTS "isValidated" boolean;
ALTER TABLE core."emailingDomain" ADD COLUMN IF NOT EXISTS "id" uuid;
ALTER TABLE core."emailingDomain" ADD COLUMN IF NOT EXISTS "createdAt" timestamp with time zone;
ALTER TABLE core."emailingDomain" ADD COLUMN IF NOT EXISTS "updatedAt" timestamp with time zone;
ALTER TABLE core."emailingDomain" ADD COLUMN IF NOT EXISTS "domain" character varying;
ALTER TABLE core."emailingDomain" ADD COLUMN IF NOT EXISTS "verificationRecords" jsonb;
ALTER TABLE core."emailingDomain" ADD COLUMN IF NOT EXISTS "verifiedAt" timestamp with time zone;
ALTER TABLE core."emailingDomain" ADD COLUMN IF NOT EXISTS "unsubscribeHostname" character varying;
ALTER TABLE core."emailingDomain" ADD COLUMN IF NOT EXISTS "unsubscribeHostnameId" character varying;
ALTER TABLE core."featureFlag" ADD COLUMN IF NOT EXISTS "id" uuid;
ALTER TABLE core."featureFlag" ADD COLUMN IF NOT EXISTS "key" text;
ALTER TABLE core."featureFlag" ADD COLUMN IF NOT EXISTS "createdAt" timestamp with time zone;
ALTER TABLE core."featureFlag" ADD COLUMN IF NOT EXISTS "updatedAt" timestamp with time zone;
ALTER TABLE core."file" ADD COLUMN IF NOT EXISTS "id" uuid;
ALTER TABLE core."file" ADD COLUMN IF NOT EXISTS "applicationId" uuid;
ALTER TABLE core."file" ADD COLUMN IF NOT EXISTS "createdAt" timestamp with time zone;
ALTER TABLE core."file" ADD COLUMN IF NOT EXISTS "updatedAt" timestamp with time zone;
ALTER TABLE core."file" ADD COLUMN IF NOT EXISTS "deletedAt" timestamp with time zone;
ALTER TABLE core."file" ADD COLUMN IF NOT EXISTS "settings" jsonb;
ALTER TABLE core."file" ADD COLUMN IF NOT EXISTS "mimeType" character varying;
ALTER TABLE core."signingKey" ADD COLUMN IF NOT EXISTS "id" uuid;
ALTER TABLE core."signingKey" ADD COLUMN IF NOT EXISTS "publicKey" character varying;
ALTER TABLE core."signingKey" ADD COLUMN IF NOT EXISTS "privateKey" character varying;
ALTER TABLE core."signingKey" ADD COLUMN IF NOT EXISTS "isCurrent" boolean;
ALTER TABLE core."signingKey" ADD COLUMN IF NOT EXISTS "revokedAt" timestamp with time zone;
ALTER TABLE core."signingKey" ADD COLUMN IF NOT EXISTS "createdAt" timestamp with time zone;
ALTER TABLE core."signingKey" ADD COLUMN IF NOT EXISTS "updatedAt" timestamp with time zone;
ALTER TABLE core."keyValuePair" ADD COLUMN IF NOT EXISTS "id" uuid;
ALTER TABLE core."keyValuePair" ADD COLUMN IF NOT EXISTS "workspaceId" uuid;
ALTER TABLE core."keyValuePair" ADD COLUMN IF NOT EXISTS "key" text;
ALTER TABLE core."keyValuePair" ADD COLUMN IF NOT EXISTS "textValueDeprecated" text;
ALTER TABLE core."keyValuePair" ADD COLUMN IF NOT EXISTS "createdAt" timestamp with time zone;
ALTER TABLE core."keyValuePair" ADD COLUMN IF NOT EXISTS "updatedAt" timestamp with time zone;
ALTER TABLE core."keyValuePair" ADD COLUMN IF NOT EXISTS "deletedAt" timestamp with time zone;
ALTER TABLE core."publicDomain" ADD COLUMN IF NOT EXISTS "id" uuid;
ALTER TABLE core."publicDomain" ADD COLUMN IF NOT EXISTS "createdAt" timestamp with time zone;
ALTER TABLE core."publicDomain" ADD COLUMN IF NOT EXISTS "updatedAt" timestamp with time zone;
ALTER TABLE core."publicDomain" ADD COLUMN IF NOT EXISTS "domain" character varying;
ALTER TABLE core."publicDomain" ADD COLUMN IF NOT EXISTS "isValidated" boolean;
ALTER TABLE core."publicDomain" ADD COLUMN IF NOT EXISTS "applicationId" uuid;
ALTER TABLE core."workspaceSSOIdentityProvider" ADD COLUMN IF NOT EXISTS "id" uuid;
ALTER TABLE core."workspaceSSOIdentityProvider" ADD COLUMN IF NOT EXISTS "createdAt" timestamp with time zone;
ALTER TABLE core."workspaceSSOIdentityProvider" ADD COLUMN IF NOT EXISTS "updatedAt" timestamp with time zone;
ALTER TABLE core."twoFactorAuthenticationMethod" ADD COLUMN IF NOT EXISTS "id" uuid;
ALTER TABLE core."twoFactorAuthenticationMethod" ADD COLUMN IF NOT EXISTS "workspaceId" uuid;
ALTER TABLE core."twoFactorAuthenticationMethod" ADD COLUMN IF NOT EXISTS "userWorkspaceId" uuid;
ALTER TABLE core."twoFactorAuthenticationMethod" ADD COLUMN IF NOT EXISTS "secret" text;
ALTER TABLE core."twoFactorAuthenticationMethod" ADD COLUMN IF NOT EXISTS "createdAt" timestamp with time zone;
ALTER TABLE core."twoFactorAuthenticationMethod" ADD COLUMN IF NOT EXISTS "updatedAt" timestamp with time zone;
ALTER TABLE core."twoFactorAuthenticationMethod" ADD COLUMN IF NOT EXISTS "deletedAt" timestamp with time zone;
ALTER TABLE core."upgradeMigration" ADD COLUMN IF NOT EXISTS "id" uuid;
ALTER TABLE core."upgradeMigration" ADD COLUMN IF NOT EXISTS "name" character varying;
ALTER TABLE core."upgradeMigration" ADD COLUMN IF NOT EXISTS "status" character varying;
ALTER TABLE core."upgradeMigration" ADD COLUMN IF NOT EXISTS "attempt" integer;
ALTER TABLE core."upgradeMigration" ADD COLUMN IF NOT EXISTS "executedByVersion" character varying;
ALTER TABLE core."upgradeMigration" ADD COLUMN IF NOT EXISTS "errorMessage" text;
ALTER TABLE core."upgradeMigration" ADD COLUMN IF NOT EXISTS "isInitial" boolean;
ALTER TABLE core."upgradeMigration" ADD COLUMN IF NOT EXISTS "workspaceId" uuid;
ALTER TABLE core."upgradeMigration" ADD COLUMN IF NOT EXISTS "createdAt" timestamp with time zone;
ALTER TABLE core."user" ADD COLUMN IF NOT EXISTS "id" uuid;
ALTER TABLE core."user" ADD COLUMN IF NOT EXISTS "createdAt" timestamp with time zone;
ALTER TABLE core."user" ADD COLUMN IF NOT EXISTS "updatedAt" timestamp with time zone;
ALTER TABLE core."user" ADD COLUMN IF NOT EXISTS "deletedAt" timestamp with time zone;
ALTER TABLE core."user" ADD COLUMN IF NOT EXISTS "locale" character varying;
ALTER TABLE core."userWorkspace" ADD COLUMN IF NOT EXISTS "id" uuid;
ALTER TABLE core."userWorkspace" ADD COLUMN IF NOT EXISTS "locale" character varying;
ALTER TABLE core."userWorkspace" ADD COLUMN IF NOT EXISTS "createdAt" timestamp with time zone;
ALTER TABLE core."userWorkspace" ADD COLUMN IF NOT EXISTS "updatedAt" timestamp with time zone;
ALTER TABLE core."userWorkspace" ADD COLUMN IF NOT EXISTS "deletedAt" timestamp with time zone;
ALTER TABLE core."workspace" ADD COLUMN IF NOT EXISTS "id" uuid;
ALTER TABLE core."workspace" ADD COLUMN IF NOT EXISTS "logoFileId" uuid;
ALTER TABLE core."workspace" ADD COLUMN IF NOT EXISTS "deletedAt" timestamp with time zone;
ALTER TABLE core."workspace" ADD COLUMN IF NOT EXISTS "createdAt" timestamp with time zone;
ALTER TABLE core."workspace" ADD COLUMN IF NOT EXISTS "updatedAt" timestamp with time zone;
ALTER TABLE core."workspace" ADD COLUMN IF NOT EXISTS "trashRetentionDays" integer;
ALTER TABLE core."workspace" ADD COLUMN IF NOT EXISTS "eventLogRetentionDays" integer;
ALTER TABLE core."workspace" ADD COLUMN IF NOT EXISTS "suspendedAt" timestamp with time zone;
ALTER TABLE core."workspace" ADD COLUMN IF NOT EXISTS "databaseSchema" character varying;
ALTER TABLE core."workspace" ADD COLUMN IF NOT EXISTS "customDomain" character varying;
ALTER TABLE core."workspace" ADD COLUMN IF NOT EXISTS "editableProfileFields" character varying;
ALTER TABLE core."workspace" ADD COLUMN IF NOT EXISTS "defaultRoleId" uuid;
ALTER TABLE core."workspace" ADD COLUMN IF NOT EXISTS "fastModel" character varying;
ALTER TABLE core."workspace" ADD COLUMN IF NOT EXISTS "smartModel" character varying;
ALTER TABLE core."workspace" ADD COLUMN IF NOT EXISTS "aiAdditionalInstructions" text;
ALTER TABLE core."workspace" ADD COLUMN IF NOT EXISTS "enabledAiModelIds" character varying;
ALTER TABLE core."workspace" ADD COLUMN IF NOT EXISTS "useRecommendedModels" boolean;
ALTER TABLE core."workspace" ADD COLUMN IF NOT EXISTS "workspaceCustomApplicationId" uuid;
ALTER TABLE core."workspace" ADD COLUMN IF NOT EXISTS "routerModel" character varying;
ALTER TABLE core."agent" ADD COLUMN IF NOT EXISTS "id" uuid;
ALTER TABLE core."agent" ADD COLUMN IF NOT EXISTS "icon" character varying;
ALTER TABLE core."agent" ADD COLUMN IF NOT EXISTS "description" text;
ALTER TABLE core."agent" ADD COLUMN IF NOT EXISTS "prompt" text;
ALTER TABLE core."agent" ADD COLUMN IF NOT EXISTS "modelId" character varying;
ALTER TABLE core."agent" ADD COLUMN IF NOT EXISTS "responseFormat" jsonb;
ALTER TABLE core."agent" ADD COLUMN IF NOT EXISTS "createdAt" timestamp with time zone;
ALTER TABLE core."agent" ADD COLUMN IF NOT EXISTS "updatedAt" timestamp with time zone;
ALTER TABLE core."agent" ADD COLUMN IF NOT EXISTS "deletedAt" timestamp with time zone;
ALTER TABLE core."agent" ADD COLUMN IF NOT EXISTS "modelConfiguration" jsonb;
ALTER TABLE core."agent" ADD COLUMN IF NOT EXISTS "evaluationInputs" text;
ALTER TABLE core."agentMessagePart" ADD COLUMN IF NOT EXISTS "id" uuid;
ALTER TABLE core."agentMessagePart" ADD COLUMN IF NOT EXISTS "workspaceId" uuid;
ALTER TABLE core."agentMessagePart" ADD COLUMN IF NOT EXISTS "orderIndex" integer;
ALTER TABLE core."agentMessagePart" ADD COLUMN IF NOT EXISTS "type" character varying;
ALTER TABLE core."agentMessagePart" ADD COLUMN IF NOT EXISTS "textContent" text;
ALTER TABLE core."agentMessagePart" ADD COLUMN IF NOT EXISTS "reasoningContent" text;
ALTER TABLE core."agentMessagePart" ADD COLUMN IF NOT EXISTS "toolName" character varying;
ALTER TABLE core."agentMessagePart" ADD COLUMN IF NOT EXISTS "toolCallId" character varying;
ALTER TABLE core."agentMessagePart" ADD COLUMN IF NOT EXISTS "toolInput" jsonb;
ALTER TABLE core."agentMessagePart" ADD COLUMN IF NOT EXISTS "toolOutput" jsonb;
ALTER TABLE core."agentMessagePart" ADD COLUMN IF NOT EXISTS "state" character varying;
ALTER TABLE core."agentMessagePart" ADD COLUMN IF NOT EXISTS "providerExecuted" boolean;
ALTER TABLE core."agentMessagePart" ADD COLUMN IF NOT EXISTS "errorMessage" text;
ALTER TABLE core."agentMessagePart" ADD COLUMN IF NOT EXISTS "errorDetails" jsonb;
ALTER TABLE core."agentMessagePart" ADD COLUMN IF NOT EXISTS "sourceUrlSourceId" character varying;
ALTER TABLE core."agentMessagePart" ADD COLUMN IF NOT EXISTS "sourceUrlUrl" character varying;
ALTER TABLE core."agentMessagePart" ADD COLUMN IF NOT EXISTS "sourceUrlTitle" character varying;
ALTER TABLE core."agentMessagePart" ADD COLUMN IF NOT EXISTS "sourceDocumentSourceId" character varying;
ALTER TABLE core."agentMessagePart" ADD COLUMN IF NOT EXISTS "sourceDocumentMediaType" character varying;
ALTER TABLE core."agentMessagePart" ADD COLUMN IF NOT EXISTS "sourceDocumentTitle" character varying;
ALTER TABLE core."agentMessagePart" ADD COLUMN IF NOT EXISTS "sourceDocumentFilename" character varying;
ALTER TABLE core."agentMessagePart" ADD COLUMN IF NOT EXISTS "fileFilename" character varying;
ALTER TABLE core."agentMessagePart" ADD COLUMN IF NOT EXISTS "fileId" uuid;
ALTER TABLE core."agentMessagePart" ADD COLUMN IF NOT EXISTS "providerMetadata" jsonb;
ALTER TABLE core."agentMessagePart" ADD COLUMN IF NOT EXISTS "createdAt" timestamp with time zone;
ALTER TABLE core."agentMessage" ADD COLUMN IF NOT EXISTS "id" uuid;
ALTER TABLE core."agentMessage" ADD COLUMN IF NOT EXISTS "workspaceId" uuid;
ALTER TABLE core."agentMessage" ADD COLUMN IF NOT EXISTS "turnId" uuid;
ALTER TABLE core."agentMessage" ADD COLUMN IF NOT EXISTS "agentId" uuid;
ALTER TABLE core."agentMessage" ADD COLUMN IF NOT EXISTS "processedAt" timestamp with time zone;
ALTER TABLE core."agentMessage" ADD COLUMN IF NOT EXISTS "createdAt" timestamp with time zone;
ALTER TABLE core."agentTurn" ADD COLUMN IF NOT EXISTS "id" uuid;
ALTER TABLE core."agentTurn" ADD COLUMN IF NOT EXISTS "workspaceId" uuid;
ALTER TABLE core."agentTurn" ADD COLUMN IF NOT EXISTS "agentId" uuid;
ALTER TABLE core."agentTurn" ADD COLUMN IF NOT EXISTS "createdAt" timestamp with time zone;
ALTER TABLE core."agentTurnEvaluation" ADD COLUMN IF NOT EXISTS "id" uuid;
ALTER TABLE core."agentTurnEvaluation" ADD COLUMN IF NOT EXISTS "workspaceId" uuid;
ALTER TABLE core."agentTurnEvaluation" ADD COLUMN IF NOT EXISTS "score" integer;
ALTER TABLE core."agentTurnEvaluation" ADD COLUMN IF NOT EXISTS "comment" text;
ALTER TABLE core."agentTurnEvaluation" ADD COLUMN IF NOT EXISTS "createdAt" timestamp with time zone;
ALTER TABLE core."agentChatThread" ADD COLUMN IF NOT EXISTS "id" uuid;
ALTER TABLE core."agentChatThread" ADD COLUMN IF NOT EXISTS "workspaceId" uuid;
ALTER TABLE core."agentChatThread" ADD COLUMN IF NOT EXISTS "userWorkspaceId" uuid;
ALTER TABLE core."agentChatThread" ADD COLUMN IF NOT EXISTS "title" character varying;
ALTER TABLE core."agentChatThread" ADD COLUMN IF NOT EXISTS "totalInputTokens" integer;
ALTER TABLE core."agentChatThread" ADD COLUMN IF NOT EXISTS "totalOutputTokens" integer;
ALTER TABLE core."agentChatThread" ADD COLUMN IF NOT EXISTS "contextWindowTokens" integer;
ALTER TABLE core."agentChatThread" ADD COLUMN IF NOT EXISTS "conversationSize" integer;
ALTER TABLE core."agentChatThread" ADD COLUMN IF NOT EXISTS "activeStreamId" character varying;
ALTER TABLE core."agentChatThread" ADD COLUMN IF NOT EXISTS "deletedAt" timestamp with time zone;
ALTER TABLE core."agentChatThread" ADD COLUMN IF NOT EXISTS "createdAt" timestamp with time zone;
ALTER TABLE core."agentChatThread" ADD COLUMN IF NOT EXISTS "updatedAt" timestamp with time zone;
ALTER TABLE core."calendarChannel" ADD COLUMN IF NOT EXISTS "id" uuid;
ALTER TABLE core."calendarChannel" ADD COLUMN IF NOT EXISTS "handle" character varying;
ALTER TABLE core."calendarChannel" ADD COLUMN IF NOT EXISTS "isContactAutoCreationEnabled" boolean;
ALTER TABLE core."calendarChannel" ADD COLUMN IF NOT EXISTS "isSyncEnabled" boolean;
ALTER TABLE core."calendarChannel" ADD COLUMN IF NOT EXISTS "syncCursor" character varying;
ALTER TABLE core."calendarChannel" ADD COLUMN IF NOT EXISTS "syncedAt" timestamp with time zone;
ALTER TABLE core."calendarChannel" ADD COLUMN IF NOT EXISTS "syncStageStartedAt" timestamp with time zone;
ALTER TABLE core."calendarChannel" ADD COLUMN IF NOT EXISTS "throttleFailureCount" integer;
ALTER TABLE core."calendarChannel" ADD COLUMN IF NOT EXISTS "webhookSubscriptionExternalId" character varying;
ALTER TABLE core."calendarChannel" ADD COLUMN IF NOT EXISTS "webhookSubscriptionExternalResourceId" character varying;
ALTER TABLE core."calendarChannel" ADD COLUMN IF NOT EXISTS "webhookSubscriptionClientState" character varying;
ALTER TABLE core."calendarChannel" ADD COLUMN IF NOT EXISTS "webhookSubscriptionExpiresAt" timestamp with time zone;
ALTER TABLE core."calendarChannel" ADD COLUMN IF NOT EXISTS "connectedAccountId" uuid;
ALTER TABLE core."calendarChannel" ADD COLUMN IF NOT EXISTS "createdAt" timestamp with time zone;
ALTER TABLE core."calendarChannel" ADD COLUMN IF NOT EXISTS "updatedAt" timestamp with time zone;
ALTER TABLE core."commandMenuItem" ADD COLUMN IF NOT EXISTS "id" uuid;
ALTER TABLE core."commandMenuItem" ADD COLUMN IF NOT EXISTS "workflowVersionId" uuid;
ALTER TABLE core."commandMenuItem" ADD COLUMN IF NOT EXISTS "frontComponentId" uuid;
ALTER TABLE core."commandMenuItem" ADD COLUMN IF NOT EXISTS "engineComponentKey" character varying;
ALTER TABLE core."commandMenuItem" ADD COLUMN IF NOT EXISTS "icon" character varying;
ALTER TABLE core."commandMenuItem" ADD COLUMN IF NOT EXISTS "shortLabel" character varying;
ALTER TABLE core."commandMenuItem" ADD COLUMN IF NOT EXISTS "payload" jsonb;
ALTER TABLE core."commandMenuItem" ADD COLUMN IF NOT EXISTS "hotKeys" text;
ALTER TABLE core."commandMenuItem" ADD COLUMN IF NOT EXISTS "conditionalAvailabilityExpression" character varying;
ALTER TABLE core."commandMenuItem" ADD COLUMN IF NOT EXISTS "availabilityObjectMetadataId" uuid;
ALTER TABLE core."commandMenuItem" ADD COLUMN IF NOT EXISTS "pageLayoutId" uuid;
ALTER TABLE core."commandMenuItem" ADD COLUMN IF NOT EXISTS "isSystemSideEffect" boolean;
ALTER TABLE core."commandMenuItem" ADD COLUMN IF NOT EXISTS "createdAt" timestamp with time zone;
ALTER TABLE core."commandMenuItem" ADD COLUMN IF NOT EXISTS "updatedAt" timestamp with time zone;
ALTER TABLE core."connectedAccount" ADD COLUMN IF NOT EXISTS "id" uuid;
ALTER TABLE core."connectedAccount" ADD COLUMN IF NOT EXISTS "handle" character varying;
ALTER TABLE core."connectedAccount" ADD COLUMN IF NOT EXISTS "provider" character varying;
ALTER TABLE core."connectedAccount" ADD COLUMN IF NOT EXISTS "accessToken" character varying;
ALTER TABLE core."connectedAccount" ADD COLUMN IF NOT EXISTS "refreshToken" character varying;
ALTER TABLE core."connectedAccount" ADD COLUMN IF NOT EXISTS "lastCredentialsRefreshedAt" timestamp with time zone;
ALTER TABLE core."connectedAccount" ADD COLUMN IF NOT EXISTS "authFailedAt" timestamp with time zone;
ALTER TABLE core."connectedAccount" ADD COLUMN IF NOT EXISTS "archivedAt" timestamp with time zone;
ALTER TABLE core."connectedAccount" ADD COLUMN IF NOT EXISTS "handleAliases" character varying;
ALTER TABLE core."connectedAccount" ADD COLUMN IF NOT EXISTS "scopes" character varying;
ALTER TABLE core."connectedAccount" ADD COLUMN IF NOT EXISTS "connectionParameters" jsonb;
ALTER TABLE core."connectedAccount" ADD COLUMN IF NOT EXISTS "lastSignedInAt" timestamp with time zone;
ALTER TABLE core."connectedAccount" ADD COLUMN IF NOT EXISTS "oidcTokenClaims" jsonb;
ALTER TABLE core."connectedAccount" ADD COLUMN IF NOT EXISTS "userWorkspaceId" uuid;
ALTER TABLE core."connectedAccount" ADD COLUMN IF NOT EXISTS "connectionProviderId" uuid;
ALTER TABLE core."connectedAccount" ADD COLUMN IF NOT EXISTS "applicationId" uuid;
ALTER TABLE core."connectedAccount" ADD COLUMN IF NOT EXISTS "name" character varying;
ALTER TABLE core."connectedAccount" ADD COLUMN IF NOT EXISTS "visibility" character varying;
ALTER TABLE core."connectedAccount" ADD COLUMN IF NOT EXISTS "createdAt" timestamp with time zone;
ALTER TABLE core."connectedAccount" ADD COLUMN IF NOT EXISTS "updatedAt" timestamp with time zone;
ALTER TABLE core."dataSource" ADD COLUMN IF NOT EXISTS "id" uuid;
ALTER TABLE core."dataSource" ADD COLUMN IF NOT EXISTS "createdAt" timestamp with time zone;
ALTER TABLE core."dataSource" ADD COLUMN IF NOT EXISTS "updatedAt" timestamp with time zone;
ALTER TABLE core."fieldMetadata" ADD COLUMN IF NOT EXISTS "id" uuid;
ALTER TABLE core."fieldMetadata" ADD COLUMN IF NOT EXISTS "objectMetadataId" uuid;
ALTER TABLE core."fieldMetadata" ADD COLUMN IF NOT EXISTS "type" character varying;
ALTER TABLE core."fieldMetadata" ADD COLUMN IF NOT EXISTS "defaultValue" jsonb;
ALTER TABLE core."fieldMetadata" ADD COLUMN IF NOT EXISTS "description" text;
ALTER TABLE core."fieldMetadata" ADD COLUMN IF NOT EXISTS "icon" character varying;
ALTER TABLE core."fieldMetadata" ADD COLUMN IF NOT EXISTS "standardOverrides" jsonb;
ALTER TABLE core."fieldMetadata" ADD COLUMN IF NOT EXISTS "isCustom" boolean;
ALTER TABLE core."fieldMetadata" ADD COLUMN IF NOT EXISTS "isSystemSideEffect" boolean;
ALTER TABLE core."fieldMetadata" ADD COLUMN IF NOT EXISTS "isUIReadOnly" boolean;
ALTER TABLE core."fieldMetadata" ADD COLUMN IF NOT EXISTS "isNullable" boolean;
ALTER TABLE core."fieldMetadata" ADD COLUMN IF NOT EXISTS "morphId" uuid;
ALTER TABLE core."fieldMetadata" ADD COLUMN IF NOT EXISTS "createdAt" timestamp with time zone;
ALTER TABLE core."fieldMetadata" ADD COLUMN IF NOT EXISTS "updatedAt" timestamp with time zone;
ALTER TABLE core."frontComponent" ADD COLUMN IF NOT EXISTS "id" uuid;
ALTER TABLE core."frontComponent" ADD COLUMN IF NOT EXISTS "description" character varying;
ALTER TABLE core."frontComponent" ADD COLUMN IF NOT EXISTS "createdAt" timestamp with time zone;
ALTER TABLE core."frontComponent" ADD COLUMN IF NOT EXISTS "updatedAt" timestamp with time zone;
ALTER TABLE core."indexFieldMetadata" ADD COLUMN IF NOT EXISTS "id" uuid;
ALTER TABLE core."indexFieldMetadata" ADD COLUMN IF NOT EXISTS "workspaceId" uuid;
ALTER TABLE core."indexFieldMetadata" ADD COLUMN IF NOT EXISTS "subFieldName" text;
ALTER TABLE core."indexFieldMetadata" ADD COLUMN IF NOT EXISTS "createdAt" timestamp with time zone;
ALTER TABLE core."indexFieldMetadata" ADD COLUMN IF NOT EXISTS "updatedAt" timestamp with time zone;
ALTER TABLE core."indexMetadata" ADD COLUMN IF NOT EXISTS "id" uuid;
ALTER TABLE core."indexMetadata" ADD COLUMN IF NOT EXISTS "createdAt" timestamp with time zone;
ALTER TABLE core."indexMetadata" ADD COLUMN IF NOT EXISTS "updatedAt" timestamp with time zone;
ALTER TABLE core."indexMetadata" ADD COLUMN IF NOT EXISTS "objectMetadataId" uuid;
ALTER TABLE core."indexMetadata" ADD COLUMN IF NOT EXISTS "indexWhereClause" text;
ALTER TABLE core."indexMetadata" ADD COLUMN IF NOT EXISTS "isSystemSideEffect" boolean;
ALTER TABLE core."logicFunction" ADD COLUMN IF NOT EXISTS "id" uuid;
ALTER TABLE core."logicFunction" ADD COLUMN IF NOT EXISTS "description" character varying;
ALTER TABLE core."logicFunction" ADD COLUMN IF NOT EXISTS "checksum" text;
ALTER TABLE core."logicFunction" ADD COLUMN IF NOT EXISTS "isBuildUpToDate" boolean;
ALTER TABLE core."logicFunction" ADD COLUMN IF NOT EXISTS "cronTriggerSettings" jsonb;
ALTER TABLE core."logicFunction" ADD COLUMN IF NOT EXISTS "databaseEventTriggerSettings" jsonb;
ALTER TABLE core."logicFunction" ADD COLUMN IF NOT EXISTS "httpRouteTriggerSettings" jsonb;
ALTER TABLE core."logicFunction" ADD COLUMN IF NOT EXISTS "serverRouteTriggerSettings" jsonb;
ALTER TABLE core."logicFunction" ADD COLUMN IF NOT EXISTS "toolTriggerSettings" jsonb;
ALTER TABLE core."logicFunction" ADD COLUMN IF NOT EXISTS "workflowActionTriggerSettings" jsonb;
ALTER TABLE core."logicFunction" ADD COLUMN IF NOT EXISTS "createdAt" timestamp with time zone;
ALTER TABLE core."logicFunction" ADD COLUMN IF NOT EXISTS "updatedAt" timestamp with time zone;
ALTER TABLE core."logicFunction" ADD COLUMN IF NOT EXISTS "deletedAt" timestamp with time zone;
ALTER TABLE core."logicFunctionLayer" ADD COLUMN IF NOT EXISTS "id" uuid;
ALTER TABLE core."logicFunctionLayer" ADD COLUMN IF NOT EXISTS "packageJson" jsonb;
ALTER TABLE core."logicFunctionLayer" ADD COLUMN IF NOT EXISTS "yarnLock" text;
ALTER TABLE core."logicFunctionLayer" ADD COLUMN IF NOT EXISTS "packageJsonChecksum" text;
ALTER TABLE core."logicFunctionLayer" ADD COLUMN IF NOT EXISTS "yarnLockChecksum" text;
ALTER TABLE core."logicFunctionLayer" ADD COLUMN IF NOT EXISTS "availablePackages" jsonb;
ALTER TABLE core."logicFunctionLayer" ADD COLUMN IF NOT EXISTS "createdAt" timestamp with time zone;
ALTER TABLE core."logicFunctionLayer" ADD COLUMN IF NOT EXISTS "updatedAt" timestamp with time zone;
ALTER TABLE core."messageChannel" ADD COLUMN IF NOT EXISTS "id" uuid;
ALTER TABLE core."messageChannel" ADD COLUMN IF NOT EXISTS "handle" character varying;
ALTER TABLE core."messageChannel" ADD COLUMN IF NOT EXISTS "isContactAutoCreationEnabled" boolean;
ALTER TABLE core."messageChannel" ADD COLUMN IF NOT EXISTS "excludeNonProfessionalEmails" boolean;
ALTER TABLE core."messageChannel" ADD COLUMN IF NOT EXISTS "excludeGroupEmails" boolean;
ALTER TABLE core."messageChannel" ADD COLUMN IF NOT EXISTS "isSyncEnabled" boolean;
ALTER TABLE core."messageChannel" ADD COLUMN IF NOT EXISTS "syncCursor" character varying;
ALTER TABLE core."messageChannel" ADD COLUMN IF NOT EXISTS "syncedAt" timestamp with time zone;
ALTER TABLE core."messageChannel" ADD COLUMN IF NOT EXISTS "syncStageStartedAt" timestamp with time zone;
ALTER TABLE core."messageChannel" ADD COLUMN IF NOT EXISTS "throttleFailureCount" integer;
ALTER TABLE core."messageChannel" ADD COLUMN IF NOT EXISTS "throttleRetryAfter" timestamp with time zone;
ALTER TABLE core."messageChannel" ADD COLUMN IF NOT EXISTS "webhookSubscriptionExternalId" character varying;
ALTER TABLE core."messageChannel" ADD COLUMN IF NOT EXISTS "webhookSubscriptionClientState" character varying;
ALTER TABLE core."messageChannel" ADD COLUMN IF NOT EXISTS "webhookSubscriptionExpiresAt" timestamp with time zone;
ALTER TABLE core."messageChannel" ADD COLUMN IF NOT EXISTS "connectedAccountId" uuid;
ALTER TABLE core."messageChannel" ADD COLUMN IF NOT EXISTS "createdAt" timestamp with time zone;
ALTER TABLE core."messageChannel" ADD COLUMN IF NOT EXISTS "updatedAt" timestamp with time zone;
ALTER TABLE core."messageFolder" ADD COLUMN IF NOT EXISTS "id" uuid;
ALTER TABLE core."messageFolder" ADD COLUMN IF NOT EXISTS "name" character varying;
ALTER TABLE core."messageFolder" ADD COLUMN IF NOT EXISTS "syncCursor" character varying;
ALTER TABLE core."messageFolder" ADD COLUMN IF NOT EXISTS "isSentFolder" boolean;
ALTER TABLE core."messageFolder" ADD COLUMN IF NOT EXISTS "isSynced" boolean;
ALTER TABLE core."messageFolder" ADD COLUMN IF NOT EXISTS "parentFolderId" character varying;
ALTER TABLE core."messageFolder" ADD COLUMN IF NOT EXISTS "externalId" character varying;
ALTER TABLE core."messageFolder" ADD COLUMN IF NOT EXISTS "messageChannelId" uuid;
ALTER TABLE core."messageFolder" ADD COLUMN IF NOT EXISTS "createdAt" timestamp with time zone;
ALTER TABLE core."messageFolder" ADD COLUMN IF NOT EXISTS "updatedAt" timestamp with time zone;
ALTER TABLE core."navigationMenuItem" ADD COLUMN IF NOT EXISTS "id" uuid;
ALTER TABLE core."navigationMenuItem" ADD COLUMN IF NOT EXISTS "userWorkspaceId" uuid;
ALTER TABLE core."navigationMenuItem" ADD COLUMN IF NOT EXISTS "targetRecordId" uuid;
ALTER TABLE core."navigationMenuItem" ADD COLUMN IF NOT EXISTS "targetObjectMetadataId" uuid;
ALTER TABLE core."navigationMenuItem" ADD COLUMN IF NOT EXISTS "viewId" uuid;
ALTER TABLE core."navigationMenuItem" ADD COLUMN IF NOT EXISTS "name" text;
ALTER TABLE core."navigationMenuItem" ADD COLUMN IF NOT EXISTS "link" text;
ALTER TABLE core."navigationMenuItem" ADD COLUMN IF NOT EXISTS "icon" text;
ALTER TABLE core."navigationMenuItem" ADD COLUMN IF NOT EXISTS "color" text;
ALTER TABLE core."navigationMenuItem" ADD COLUMN IF NOT EXISTS "folderId" uuid;
ALTER TABLE core."navigationMenuItem" ADD COLUMN IF NOT EXISTS "pageLayoutId" uuid;
ALTER TABLE core."navigationMenuItem" ADD COLUMN IF NOT EXISTS "createdAt" timestamp with time zone;
ALTER TABLE core."navigationMenuItem" ADD COLUMN IF NOT EXISTS "updatedAt" timestamp with time zone;
ALTER TABLE core."objectMetadata" ADD COLUMN IF NOT EXISTS "id" uuid;
ALTER TABLE core."objectMetadata" ADD COLUMN IF NOT EXISTS "dataSourceId" uuid;
ALTER TABLE core."objectMetadata" ADD COLUMN IF NOT EXISTS "description" text;
ALTER TABLE core."objectMetadata" ADD COLUMN IF NOT EXISTS "icon" character varying;
ALTER TABLE core."objectMetadata" ADD COLUMN IF NOT EXISTS "color" text;
ALTER TABLE core."objectMetadata" ADD COLUMN IF NOT EXISTS "standardOverrides" jsonb;
ALTER TABLE core."objectMetadata" ADD COLUMN IF NOT EXISTS "isCustom" boolean;
ALTER TABLE core."objectMetadata" ADD COLUMN IF NOT EXISTS "isUIReadOnly" boolean;
ALTER TABLE core."objectMetadata" ADD COLUMN IF NOT EXISTS "duplicateCriteria" jsonb;
ALTER TABLE core."objectMetadata" ADD COLUMN IF NOT EXISTS "shortcut" character varying;
ALTER TABLE core."objectMetadata" ADD COLUMN IF NOT EXISTS "labelIdentifierFieldMetadataId" uuid;
ALTER TABLE core."objectMetadata" ADD COLUMN IF NOT EXISTS "imageIdentifierFieldMetadataId" uuid;
ALTER TABLE core."objectMetadata" ADD COLUMN IF NOT EXISTS "createdAt" timestamp with time zone;
ALTER TABLE core."objectMetadata" ADD COLUMN IF NOT EXISTS "updatedAt" timestamp with time zone;
ALTER TABLE core."fieldPermission" ADD COLUMN IF NOT EXISTS "id" uuid;
ALTER TABLE core."fieldPermission" ADD COLUMN IF NOT EXISTS "roleId" uuid;
ALTER TABLE core."fieldPermission" ADD COLUMN IF NOT EXISTS "objectMetadataId" uuid;
ALTER TABLE core."fieldPermission" ADD COLUMN IF NOT EXISTS "fieldMetadataId" uuid;
ALTER TABLE core."fieldPermission" ADD COLUMN IF NOT EXISTS "canReadFieldValue" boolean;
ALTER TABLE core."fieldPermission" ADD COLUMN IF NOT EXISTS "canUpdateFieldValue" boolean;
ALTER TABLE core."fieldPermission" ADD COLUMN IF NOT EXISTS "createdAt" timestamp with time zone;
ALTER TABLE core."fieldPermission" ADD COLUMN IF NOT EXISTS "updatedAt" timestamp with time zone;
ALTER TABLE core."objectPermission" ADD COLUMN IF NOT EXISTS "id" uuid;
ALTER TABLE core."objectPermission" ADD COLUMN IF NOT EXISTS "roleId" uuid;
ALTER TABLE core."objectPermission" ADD COLUMN IF NOT EXISTS "objectMetadataId" uuid;
ALTER TABLE core."objectPermission" ADD COLUMN IF NOT EXISTS "canReadObjectRecords" boolean;
ALTER TABLE core."objectPermission" ADD COLUMN IF NOT EXISTS "canUpdateObjectRecords" boolean;
ALTER TABLE core."objectPermission" ADD COLUMN IF NOT EXISTS "canSoftDeleteObjectRecords" boolean;
ALTER TABLE core."objectPermission" ADD COLUMN IF NOT EXISTS "canDestroyObjectRecords" boolean;
ALTER TABLE core."objectPermission" ADD COLUMN IF NOT EXISTS "createdAt" timestamp with time zone;
ALTER TABLE core."objectPermission" ADD COLUMN IF NOT EXISTS "updatedAt" timestamp with time zone;
ALTER TABLE core."pageLayout" ADD COLUMN IF NOT EXISTS "id" uuid;
ALTER TABLE core."pageLayout" ADD COLUMN IF NOT EXISTS "objectMetadataId" uuid;
ALTER TABLE core."pageLayout" ADD COLUMN IF NOT EXISTS "defaultTabToFocusOnMobileAndSidePanelId" uuid;
ALTER TABLE core."pageLayout" ADD COLUMN IF NOT EXISTS "isSystemSideEffect" boolean;
ALTER TABLE core."pageLayout" ADD COLUMN IF NOT EXISTS "createdAt" timestamp with time zone;
ALTER TABLE core."pageLayout" ADD COLUMN IF NOT EXISTS "updatedAt" timestamp with time zone;
ALTER TABLE core."pageLayout" ADD COLUMN IF NOT EXISTS "deletedAt" timestamp with time zone;
ALTER TABLE core."pageLayoutTab" ADD COLUMN IF NOT EXISTS "id" uuid;
ALTER TABLE core."pageLayoutTab" ADD COLUMN IF NOT EXISTS "position" double precision;
ALTER TABLE core."pageLayoutTab" ADD COLUMN IF NOT EXISTS "pageLayoutId" uuid;
ALTER TABLE core."pageLayoutTab" ADD COLUMN IF NOT EXISTS "icon" character varying;
ALTER TABLE core."pageLayoutTab" ADD COLUMN IF NOT EXISTS "isSystemSideEffect" boolean;
ALTER TABLE core."pageLayoutTab" ADD COLUMN IF NOT EXISTS "createdAt" timestamp with time zone;
ALTER TABLE core."pageLayoutTab" ADD COLUMN IF NOT EXISTS "updatedAt" timestamp with time zone;
ALTER TABLE core."pageLayoutTab" ADD COLUMN IF NOT EXISTS "deletedAt" timestamp with time zone;
ALTER TABLE core."pageLayoutWidget" ADD COLUMN IF NOT EXISTS "id" uuid;
ALTER TABLE core."pageLayoutWidget" ADD COLUMN IF NOT EXISTS "pageLayoutTabId" uuid;
ALTER TABLE core."pageLayoutWidget" ADD COLUMN IF NOT EXISTS "objectMetadataId" uuid;
ALTER TABLE core."pageLayoutWidget" ADD COLUMN IF NOT EXISTS "conditionalDisplay" jsonb;
ALTER TABLE core."pageLayoutWidget" ADD COLUMN IF NOT EXISTS "conditionalAvailabilityExpression" character varying;
ALTER TABLE core."pageLayoutWidget" ADD COLUMN IF NOT EXISTS "gridPosition" jsonb;
ALTER TABLE core."pageLayoutWidget" ADD COLUMN IF NOT EXISTS "position" jsonb;
ALTER TABLE core."pageLayoutWidget" ADD COLUMN IF NOT EXISTS "configuration" jsonb;
ALTER TABLE core."pageLayoutWidget" ADD COLUMN IF NOT EXISTS "isSystemSideEffect" boolean;
ALTER TABLE core."pageLayoutWidget" ADD COLUMN IF NOT EXISTS "createdAt" timestamp with time zone;
ALTER TABLE core."pageLayoutWidget" ADD COLUMN IF NOT EXISTS "updatedAt" timestamp with time zone;
ALTER TABLE core."pageLayoutWidget" ADD COLUMN IF NOT EXISTS "deletedAt" timestamp with time zone;
ALTER TABLE core."permissionFlag" ADD COLUMN IF NOT EXISTS "id" uuid;
ALTER TABLE core."permissionFlag" ADD COLUMN IF NOT EXISTS "key" character varying;
ALTER TABLE core."permissionFlag" ADD COLUMN IF NOT EXISTS "label" character varying;
ALTER TABLE core."permissionFlag" ADD COLUMN IF NOT EXISTS "description" text;
ALTER TABLE core."permissionFlag" ADD COLUMN IF NOT EXISTS "icon" character varying;
ALTER TABLE core."permissionFlag" ADD COLUMN IF NOT EXISTS "permissionType" character varying;
ALTER TABLE core."permissionFlag" ADD COLUMN IF NOT EXISTS "createdAt" timestamp with time zone;
ALTER TABLE core."permissionFlag" ADD COLUMN IF NOT EXISTS "updatedAt" timestamp with time zone;
ALTER TABLE core."role" ADD COLUMN IF NOT EXISTS "id" uuid;
ALTER TABLE core."role" ADD COLUMN IF NOT EXISTS "description" text;
ALTER TABLE core."role" ADD COLUMN IF NOT EXISTS "icon" character varying;
ALTER TABLE core."role" ADD COLUMN IF NOT EXISTS "createdAt" timestamp with time zone;
ALTER TABLE core."role" ADD COLUMN IF NOT EXISTS "updatedAt" timestamp with time zone;
ALTER TABLE core."roleTarget" ADD COLUMN IF NOT EXISTS "id" uuid;
ALTER TABLE core."roleTarget" ADD COLUMN IF NOT EXISTS "roleId" uuid;
ALTER TABLE core."roleTarget" ADD COLUMN IF NOT EXISTS "userWorkspaceId" uuid;
ALTER TABLE core."roleTarget" ADD COLUMN IF NOT EXISTS "agentId" uuid;
ALTER TABLE core."roleTarget" ADD COLUMN IF NOT EXISTS "apiKeyId" uuid;
ALTER TABLE core."roleTarget" ADD COLUMN IF NOT EXISTS "createdAt" timestamp with time zone;
ALTER TABLE core."roleTarget" ADD COLUMN IF NOT EXISTS "updatedAt" timestamp with time zone;
ALTER TABLE core."rowLevelPermissionPredicateGroup" ADD COLUMN IF NOT EXISTS "id" uuid;
ALTER TABLE core."rowLevelPermissionPredicateGroup" ADD COLUMN IF NOT EXISTS "parentRowLevelPermissionPredicateGroupId" uuid;
ALTER TABLE core."rowLevelPermissionPredicateGroup" ADD COLUMN IF NOT EXISTS "roleId" uuid;
ALTER TABLE core."rowLevelPermissionPredicateGroup" ADD COLUMN IF NOT EXISTS "objectMetadataId" uuid;
ALTER TABLE core."rowLevelPermissionPredicateGroup" ADD COLUMN IF NOT EXISTS "createdAt" timestamp with time zone;
ALTER TABLE core."rowLevelPermissionPredicateGroup" ADD COLUMN IF NOT EXISTS "updatedAt" timestamp with time zone;
ALTER TABLE core."rowLevelPermissionPredicateGroup" ADD COLUMN IF NOT EXISTS "deletedAt" timestamp with time zone;
ALTER TABLE core."rowLevelPermissionPredicate" ADD COLUMN IF NOT EXISTS "id" uuid;
ALTER TABLE core."rowLevelPermissionPredicate" ADD COLUMN IF NOT EXISTS "fieldMetadataId" uuid;
ALTER TABLE core."rowLevelPermissionPredicate" ADD COLUMN IF NOT EXISTS "objectMetadataId" uuid;
ALTER TABLE core."rowLevelPermissionPredicate" ADD COLUMN IF NOT EXISTS "value" jsonb;
ALTER TABLE core."rowLevelPermissionPredicate" ADD COLUMN IF NOT EXISTS "subFieldName" text;
ALTER TABLE core."rowLevelPermissionPredicate" ADD COLUMN IF NOT EXISTS "workspaceMemberFieldMetadataId" uuid;
ALTER TABLE core."rowLevelPermissionPredicate" ADD COLUMN IF NOT EXISTS "workspaceMemberSubFieldName" text;
ALTER TABLE core."rowLevelPermissionPredicate" ADD COLUMN IF NOT EXISTS "rowLevelPermissionPredicateGroupId" uuid;
ALTER TABLE core."rowLevelPermissionPredicate" ADD COLUMN IF NOT EXISTS "roleId" uuid;
ALTER TABLE core."rowLevelPermissionPredicate" ADD COLUMN IF NOT EXISTS "createdAt" timestamp with time zone;
ALTER TABLE core."rowLevelPermissionPredicate" ADD COLUMN IF NOT EXISTS "updatedAt" timestamp with time zone;
ALTER TABLE core."rowLevelPermissionPredicate" ADD COLUMN IF NOT EXISTS "deletedAt" timestamp with time zone;
ALTER TABLE core."searchFieldMetadata" ADD COLUMN IF NOT EXISTS "id" uuid;
ALTER TABLE core."searchFieldMetadata" ADD COLUMN IF NOT EXISTS "objectMetadataId" uuid;
ALTER TABLE core."searchFieldMetadata" ADD COLUMN IF NOT EXISTS "fieldMetadataId" uuid;
ALTER TABLE core."searchFieldMetadata" ADD COLUMN IF NOT EXISTS "position" double precision;
ALTER TABLE core."searchFieldMetadata" ADD COLUMN IF NOT EXISTS "createdAt" timestamp with time zone;
ALTER TABLE core."searchFieldMetadata" ADD COLUMN IF NOT EXISTS "updatedAt" timestamp with time zone;
ALTER TABLE core."skill" ADD COLUMN IF NOT EXISTS "id" uuid;
ALTER TABLE core."skill" ADD COLUMN IF NOT EXISTS "icon" character varying;
ALTER TABLE core."skill" ADD COLUMN IF NOT EXISTS "description" text;
ALTER TABLE core."skill" ADD COLUMN IF NOT EXISTS "content" text;
ALTER TABLE core."skill" ADD COLUMN IF NOT EXISTS "createdAt" timestamp with time zone;
ALTER TABLE core."skill" ADD COLUMN IF NOT EXISTS "updatedAt" timestamp with time zone;
ALTER TABLE core."view" ADD COLUMN IF NOT EXISTS "id" uuid;
ALTER TABLE core."view" ADD COLUMN IF NOT EXISTS "name" text;
ALTER TABLE core."view" ADD COLUMN IF NOT EXISTS "objectMetadataId" uuid;
ALTER TABLE core."view" ADD COLUMN IF NOT EXISTS "icon" text;
ALTER TABLE core."view" ADD COLUMN IF NOT EXISTS "isCompact" boolean;
ALTER TABLE core."view" ADD COLUMN IF NOT EXISTS "isCustom" boolean;
ALTER TABLE core."view" ADD COLUMN IF NOT EXISTS "kanbanAggregateOperationFieldMetadataId" uuid;
ALTER TABLE core."view" ADD COLUMN IF NOT EXISTS "calendarFieldMetadataId" uuid;
ALTER TABLE core."view" ADD COLUMN IF NOT EXISTS "mainGroupByFieldMetadataId" uuid;
ALTER TABLE core."view" ADD COLUMN IF NOT EXISTS "shouldHideEmptyGroups" boolean;
ALTER TABLE core."view" ADD COLUMN IF NOT EXISTS "kanbanColumnWidth" integer;
ALTER TABLE core."view" ADD COLUMN IF NOT EXISTS "createdAt" timestamp with time zone;
ALTER TABLE core."view" ADD COLUMN IF NOT EXISTS "updatedAt" timestamp with time zone;
ALTER TABLE core."view" ADD COLUMN IF NOT EXISTS "deletedAt" timestamp with time zone;
ALTER TABLE core."view" ADD COLUMN IF NOT EXISTS "anyFieldFilterValue" text;
ALTER TABLE core."view" ADD COLUMN IF NOT EXISTS "isSystemSideEffect" boolean;
ALTER TABLE core."view" ADD COLUMN IF NOT EXISTS "createdByUserWorkspaceId" uuid;
ALTER TABLE core."viewField" ADD COLUMN IF NOT EXISTS "id" uuid;
ALTER TABLE core."viewField" ADD COLUMN IF NOT EXISTS "fieldMetadataId" uuid;
ALTER TABLE core."viewField" ADD COLUMN IF NOT EXISTS "size" integer;
ALTER TABLE core."viewField" ADD COLUMN IF NOT EXISTS "viewId" uuid;
ALTER TABLE core."viewField" ADD COLUMN IF NOT EXISTS "viewFieldGroupId" uuid;
ALTER TABLE core."viewField" ADD COLUMN IF NOT EXISTS "isSystemSideEffect" boolean;
ALTER TABLE core."viewField" ADD COLUMN IF NOT EXISTS "createdAt" timestamp with time zone;
ALTER TABLE core."viewField" ADD COLUMN IF NOT EXISTS "updatedAt" timestamp with time zone;
ALTER TABLE core."viewField" ADD COLUMN IF NOT EXISTS "deletedAt" timestamp with time zone;
ALTER TABLE core."viewFieldGroup" ADD COLUMN IF NOT EXISTS "id" uuid;
ALTER TABLE core."viewFieldGroup" ADD COLUMN IF NOT EXISTS "name" text;
ALTER TABLE core."viewFieldGroup" ADD COLUMN IF NOT EXISTS "viewId" uuid;
ALTER TABLE core."viewFieldGroup" ADD COLUMN IF NOT EXISTS "createdAt" timestamp with time zone;
ALTER TABLE core."viewFieldGroup" ADD COLUMN IF NOT EXISTS "updatedAt" timestamp with time zone;
ALTER TABLE core."viewFieldGroup" ADD COLUMN IF NOT EXISTS "deletedAt" timestamp with time zone;
ALTER TABLE core."viewFilter" ADD COLUMN IF NOT EXISTS "id" uuid;
ALTER TABLE core."viewFilter" ADD COLUMN IF NOT EXISTS "fieldMetadataId" uuid;
ALTER TABLE core."viewFilter" ADD COLUMN IF NOT EXISTS "value" jsonb;
ALTER TABLE core."viewFilter" ADD COLUMN IF NOT EXISTS "viewFilterGroupId" uuid;
ALTER TABLE core."viewFilter" ADD COLUMN IF NOT EXISTS "subFieldName" text;
ALTER TABLE core."viewFilter" ADD COLUMN IF NOT EXISTS "relationTargetFieldMetadataId" uuid;
ALTER TABLE core."viewFilter" ADD COLUMN IF NOT EXISTS "viewId" uuid;
ALTER TABLE core."viewFilter" ADD COLUMN IF NOT EXISTS "createdAt" timestamp with time zone;
ALTER TABLE core."viewFilter" ADD COLUMN IF NOT EXISTS "updatedAt" timestamp with time zone;
ALTER TABLE core."viewFilter" ADD COLUMN IF NOT EXISTS "deletedAt" timestamp with time zone;
ALTER TABLE core."viewFilterGroup" ADD COLUMN IF NOT EXISTS "id" uuid;
ALTER TABLE core."viewFilterGroup" ADD COLUMN IF NOT EXISTS "parentViewFilterGroupId" uuid;
ALTER TABLE core."viewFilterGroup" ADD COLUMN IF NOT EXISTS "viewId" uuid;
ALTER TABLE core."viewFilterGroup" ADD COLUMN IF NOT EXISTS "createdAt" timestamp with time zone;
ALTER TABLE core."viewFilterGroup" ADD COLUMN IF NOT EXISTS "updatedAt" timestamp with time zone;
ALTER TABLE core."viewFilterGroup" ADD COLUMN IF NOT EXISTS "deletedAt" timestamp with time zone;
ALTER TABLE core."viewGroup" ADD COLUMN IF NOT EXISTS "id" uuid;
ALTER TABLE core."viewGroup" ADD COLUMN IF NOT EXISTS "fieldValue" text;
ALTER TABLE core."viewGroup" ADD COLUMN IF NOT EXISTS "viewId" uuid;
ALTER TABLE core."viewGroup" ADD COLUMN IF NOT EXISTS "createdAt" timestamp with time zone;
ALTER TABLE core."viewGroup" ADD COLUMN IF NOT EXISTS "updatedAt" timestamp with time zone;
ALTER TABLE core."viewGroup" ADD COLUMN IF NOT EXISTS "deletedAt" timestamp with time zone;
ALTER TABLE core."viewSort" ADD COLUMN IF NOT EXISTS "id" uuid;
ALTER TABLE core."viewSort" ADD COLUMN IF NOT EXISTS "fieldMetadataId" uuid;
ALTER TABLE core."viewSort" ADD COLUMN IF NOT EXISTS "subFieldName" character varying;
ALTER TABLE core."viewSort" ADD COLUMN IF NOT EXISTS "viewId" uuid;
ALTER TABLE core."viewSort" ADD COLUMN IF NOT EXISTS "createdAt" timestamp with time zone;
ALTER TABLE core."viewSort" ADD COLUMN IF NOT EXISTS "updatedAt" timestamp with time zone;
ALTER TABLE core."viewSort" ADD COLUMN IF NOT EXISTS "deletedAt" timestamp with time zone;
ALTER TABLE core."webhook" ADD COLUMN IF NOT EXISTS "id" uuid;
ALTER TABLE core."webhook" ADD COLUMN IF NOT EXISTS "description" character varying;
ALTER TABLE core."webhook" ADD COLUMN IF NOT EXISTS "createdAt" timestamp with time zone;
ALTER TABLE core."webhook" ADD COLUMN IF NOT EXISTS "updatedAt" timestamp with time zone;
ALTER TABLE core."webhook" ADD COLUMN IF NOT EXISTS "deletedAt" timestamp with time zone;